### ISSUE TITLE
GNS3VM on HyperV (Windows 10) -frequent kernel panic

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-server#1806] opened 2020-08-08 14:11 UTC
Hi guys

Here is what I am seeing. o far the only pattern I am seeing here is that it happens when I am away from my computer or when the VM has been idle for a long time. This would like the 5th or 6th crash 

![vmconnect_3NI1r2ZfMS](https://user-images.githubusercontent.com/17384308/89712538-8550b180-d95f-11ea-85b8-4f0b6f30ead2.png)

**Comment by grossmj** [comment] 2020-08-12 06:49
This is similar to https://github.com/GNS3/gns3-gui/issues/2815 and looks like it is not only GNS3. I really don't know what is wrong with Hyper-V.

**Comment by 1001QAdotNET** [comment] 2020-08-12 13:21
Could be. What I notices was that if I open up the lab but I do not start any node the VM is stable ...noticed that by accident as I worked on something else and I totally forgot about the started GNS3 VM

**Comment by morton-a** [comment] 2020-12-27 21:34
Ahhh, I have just seen this.  I experienced this issue with 2.2.16 and 2.2.17 on Hyper-V Server 2019 as well.  As @1001QAdotNET said this does not appear to happen if no nodes have been started since GNS3 has booted.  If a node has been started (and even if stopped) the system will eventually crash as shown above.  The error message is the same each time.

**Comment by morton-a** [comment] 2020-12-29 14:11
I may have resolved this somehow by making the following changes:

- Changing Qemu version to 2.11.1 - this did not resolve the issue on its own previously
- Turned off certain Hyper-V 'Integration Services' on the GNS3 VM:
  - Data Exchange
  - Heartbeat
  - Backup (volume shadow copy)
  - Guest services

One strange thing to note is that I had to reinstall Qemu via the GNS3 GUI just before the above, as I was receiving errors that the service could not be contacted.

It has been more than 24 hours since I had my last crash.  This normally happens a lot sooner, so I'll keep these settings running until the end of the week and then update.

**Comment by bile0026** [comment] 2020-12-30 06:12
I've attempted with Qemu 2.11.1, and 3.1.0, and with settings mentioned by @morton-a Still crashing. One thing I notice, is it only seems to crash when I try and run IOU images at the same time as the CentOS Cloud guest. If I run just the Guest machine by itself it runs just fine until I try and start an IOU device. Instant crash. As well as running IOU devices is fine until I start the CentOS guest.

**Comment by morton-a** [comment] 2020-12-30 12:05
@bile0026.  My GNS3 server threw the Kernel Panic last night, so the issue is still present.  Note, I am not using IOU and I am not sure if these two issues are related: I think the issue on this thread is that Qemu somehow causes a Kernel Panic after running for some time - CentOS will be in Qemu.  Note, the Kernel Panic is always the same.  Do you get the same Kernel Panic from IOU shown above?

Note, my latest test has been to simply uninstall gpgv.

**Comment by bile0026** [comment] 2020-12-30 14:13
@morton-a yes, same kernel panic with IOU. At first I thought it was resource exhaustion but after some further digging that doesn't seem to be the case. I was able to run 3 IOU devices for over an hour and as soon as I booted the centos box it panicked. Was able to reproduce multiple times. And vice versa, running the centos box, then booting an IOU device. Instant panic.

**Comment by morton-a** [comment] 2021-01-07 19:38
@bile0026, just an FYI. I still had the same issues after my changes.  I have now reverted to having the Zabbix monitor auto restart the VM once it becomes unavailable for 5 minutes: a normal reboot takes less than 20 seconds.

**Comment by bile0026** [comment] 2021-01-07 19:51
@morton-a rebooting for me at least, doesn't solve the problem since as soon as I launch the 2 devices together it's an instant crash, and I need to run them in parallel. Need to figure out what's causing it so I can run both.

**Comment by JacBra** [comment] 2021-09-27 08:37
Hi, this is quite an annoying thing. Happens with my config also on a regular basis. Anyone found a solution in the meantime?

**Closed** 2023-01-30 07:54 UTC
