### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#218] opened 2015-06-05 04:10 UTC
https://app.getsentry.com/gns3/gns3-server/group/67903422/

```
IndexError: tuple index out of range
  File "gns3server/web/route.py", line 140, in control_schema
    yield from func(request, response)
  File "gns3server/handlers/api/qemu_handler.py", line 146, in start
    yield from vm.start()
  File "gns3server/modules/qemu/qemu_vm.py", line 573, in start
    self._command = yield from self._build_command()
  File "gns3server/modules/qemu/qemu_vm.py", line 1066, in _build_command
    command.extend(self._network_options())
  File "gns3server/modules/qemu/qemu_vm.py", line 1030, in _network_options
    network_options.extend(["-device", "{},mac={},netdev=gns3-{},id=net-{}".format(self._adapter_type, mac)])
```

**Comment by noplay** [comment] 2015-06-05 09:46
Duplicate of #219 the two crash was send by the same user.

**Closed by noplay** 2015-06-05 09:46 UTC
Labels: bug
