### ISSUE TITLE
After upgrade to v2.1.3 'Unable to create UDP NIO' when trying to open previous projects

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1271] opened 2018-01-25 10:30 UTC
From gns3 community forum:
https://gns3.com/qa/-unable-to-create-udp-nio-when-t

Found an similar issue here that was solved then:
https://github.com/GNS3/gns3-server/issues/825

----------------

Hi GNS3 team, right now i have a problem with GNS3 2.1.3
 
before i update the GNS3, i was on 2.1.1 version, and it worked perfectly.
 
Today i updated it to 2.1.3 version, and after that, i cannot open any of my previous projects.
 
when i try to open a previous project, a message appear.
 

> 2018-01-24 21:08:19 CRITICAL topology.py:222 Dynamips error when running command 'nio create_udp udp-1e8bae55-4645-420c-b8b4-0ad5d9b2a429 10001 127.0.0.1 10000
> ': unable to create UDP NIO
> PORT=5900
> 2018-01-24 21:09:34 CRITICAL topology.py:222 Dynamips error when running command 'nio create_udp udp-687795f3-9760-4a9c-bc43-5801f1ddf358 10001 127.0.0.1 10000
> ': unable to create UDP NIO

 
![image](https://user-images.githubusercontent.com/1716020/35383634-15d5c014-01c3-11e8-8f74-e1a76d5b3724.png)

 
 
tried to change the UDP tunneling port range minimum to 10001 but still no result.
 
the UDP tunneling port range is in default number, min 10000 and max 20000
 
btw, i am using Linux Mint 18.3 sylvia
 
can you guys help me solve the problem?
 
thanks before.

**Comment by grossmj** [comment] 2018-01-29 10:54
User solved this issue.

**Comment by grossmj** [comment] 2018-03-31 04:43
I am experiencing this issue too.

**Comment by grossmj** [comment] 2018-03-31 06:08
There was an issue in Dynamips fixed in https://github.com/GNS3/dynamips/commit/4f58a57e1dcd489d1c5592b42c8176a849573574

Please download Dynamips version 0.2.18 if you experience this issue: https://github.com/GNS3/dynamips/releases/tag/v0.2.18

**Comment by grossmj** [comment] 2018-03-31 06:11
@ziajka please make sure we have version 0.2.18 released on our ppa, thanks :+1:

**Comment by ziajka** [comment] 2018-04-03 07:38
@grossmj released.

**Comment by Menelan** [comment] 2019-10-11 21:35
Today I had the same problem, I tried all the solutions proposed on different site, none worked ...
Reinstalling GN3 with and without restarting the computer, removing gns3 registry keys and more.
I finally found the solution and I want to share it because I think it will help somebody.
I found the solution with a stroke of luck, it came from the software **nvidia Geforce Experience**, because when I did not have it I could open my projects, but once installed I could not do it anymore, I did the test several times and **the problem comes from the GeForce Experience software**.
I hope this will help some person.

**Comment by Deadmaus2630** [comment] 2019-10-13 00:37
Hello bro, I'm from Peru, I was killing my head that it could be the mistake, thank you very much for your contribution, you really saved my life since I had a project of my career and I could not open it and there is not much information about this error

**Comment by grossmj** [comment] 2019-10-13 14:47
@Deadmaus2630 did you encountered the exact same problem with GeForce Experience software?

**Comment by Deadmaus2630** [comment] 2019-10-13 15:57
if you know if it is a program error or a program error or a software error
in my case it is a windows 10 pro

**Comment by Deadmaus2630** [comment] 2019-10-15 15:40
Hello, if I found the same error, do you know if it is an error in the nvidia program or is it from gns3?

**Comment by xJoaoMonteiro** [comment] 2019-10-17 08:06
I was facing the same problem and removing nvidia Geforce Experience software solved my problem. Thanks a lot guys

**Comment by Menelan** [comment] 2019-10-17 10:06
No problem. I hope the problem will be solved quickly.

**Comment by mazi6v6** [comment] 2019-10-17 18:15
@Menelan  Thanks a lot! My problem was solved!

**Comment by phoenix2291** [comment] 2019-10-21 16:49
@grossmj I'm facing the same issue about the Geforce experience. I issued a ticket to Nvidia and requested the developers from GNS3 to check from there side.

**Comment by Menelan** [comment] 2019-10-29 10:27
@phoenix2291 The solution for the moment is to go to "control panel" and "uninstall a program", just uninstall "Nvidia GeForce Experience", the driver will always be installed.
There is no other solution known at the moment, the problem can simply come from a registry key modify by the software "Nvidia" which would prevent the opening of the projects, but that can be more complex, no idea from my side, I have not looked enough for the moment.

**Comment by grossmj** [comment] 2019-10-30 07:14
Need to check if I can understand why "Nvidia GeForce Experience" conflicts with Dynamips.

**Comment by julio-rs713** [comment] 2019-11-02 02:49
My case it's not because i has upgraded the software, it has happened with a new installation and a new project with this, but maybe this can be of help to somebody. By the way, my mother language isn't english.
I has a similar problem: I saved my project with other name and there was a problem with it, the project was created but i was unable to open the new project and the original, with the message:
_Dynamips error when running command 'nio create_udp udp-547de233-2b2f-40f6-b802-f96cec82335f 10010 127.0.0.1 10009
': unable to create UDP NIO._
Just in case, I tried creating a new proyect, it works well, and I saved it with other name (it worked). After that i opend my original project with the error, and this works. I saved the original project with other name, and also works, I just repeated with a new project the events that cause my project to have that error, and that fixes it.

**Comment by keithallenjackson** [comment] 2019-11-04 17:21
Just confirmed this fix for me: removing GeForce Experience fixed all issues regarding the "unable to create UDP NIO" error. Seriously curios as to why GeForce Experience would cause this problem.

**Comment by cioby23** [comment] 2019-11-04 18:30
I found this knowledge base article on nVidia support site
https://nvidia.custhelp.com/app/answers/detail/a_id/4566/~/error-message-0x8008201c
It seems Nvidia software uses the same port range TCP/UDP 10000 - 20000 which might conflict with the GNS3 console port range

**Comment by kervinroz** [comment] 2019-11-05 09:19
Guys thanks a lot! I recently purchased a new Graphics Card and Installed Nvidia Geforce Experience. All of a sudden, my GNS3 started working cranky. So I started to uninstall the NGE program. Things went smooth and got fixed! :D

**Comment by AndreDias96** [comment] 2019-11-05 23:01
> Today I had the same problem, I tried all the solutions proposed on different site, none worked ...
> Reinstalling GN3 with and without restarting the computer, removing gns3 registry keys and more.
> I finally found the solution and I want to share it because I think it will help somebody.
> I found the solution with a stroke of luck, it came from the software **nvidia Geforce Experience**, because when I did not have it I could open my projects, but once installed I could not do it anymore, I did the test several times and **the problem comes from the GeForce Experience software**.
> I hope this will help some person.

Thanks for help. I was thinking that I would have to format the computer.

**Comment by grossmj** [comment] 2019-11-06 04:24
> It seems Nvidia software uses the same port range TCP/UDP 10000 - 20000 which might conflict with the GNS3 console port range.

I am going to change the default UDP port range to be 20000 - 30000 in our next release. I hope this is going to prevent the issue to happen again.

**Comment by GuruOz** [comment] 2019-11-08 22:59
Just to confirm, i tried downloading the linked Dynamips version 0.2.18. That did not work. But removing NVIDIA GeForce Experience fixed the issue

**Comment by vint66** [comment] 2019-11-13 22:52
Hi Jeremy,

Just want to mention that server config still has old port. Does it make sense to change it here also?

; First console port of the range allocated to devices
console_start_port_range = 5000
; Last console port of the range allocated to devices
console_end_port_range = 10000
; First port of the range allocated for inter-device communication. Two ports are allocated per link.
udp_start_port_range = 10000
; Last port of the range allocated for inter-device communication. Two ports are allocated per link
udp_end_port_range = 20000

**Comment by Spartan-X** [comment] 2019-12-10 22:25
Thanks killing the Nvidia Services worked!! thanks very much

> Today I had the same problem, I tried all the solutions proposed on different site, none worked ...
> Reinstalling GN3 with and without restarting the computer, removing gns3 registry keys and more.
> I finally found the solution and I want to share it because I think it will help somebody.
> I found the solution with a stroke of luck, it came from the software **nvidia Geforce Experience**, because when I did not have it I could open my projects, but once installed I could not do it anymore, I did the test several times and **the problem comes from the GeForce Experience software**.
> I hope this will help some person.

**Comment by Solidnetwork** [comment] 2019-12-15 14:51
Hi all,

Just want to inform removing nvidia Gefore Experience worked for me also. It start working after uninstall instantly.

**Comment by vasiliyaltunin** [comment] 2020-01-02 05:55
I have same issue on windows 10 whin 2.2.3 version
Fixing file

C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini 

and set 

udp_start_port_range = 20000
udp_end_port_range = 30000

resolve this issue i think on windows config must be changed by default!

**Comment by bsweeney83** [comment] 2020-01-04 03:45
This issue has been driving me nuts for months while trying to use GNS3 to study for the CCNA. Every time I would create a project, I couldn't open it after closing GNS3 and would have to start from scratch every time. Very annoying to say the least. I found multiple threads in the GNS3 Community for this error, but nobody provided an actual fix/workaround in any of them. Glad I found this thread by clicking on a Google image with the error. I just uninstalled Geforce Experience and now I can open old projects. This sucks though because I like having Geforce Experience installed.

**Comment by bsweeney83** [comment] 2020-01-04 03:56
> I have same issue on windows 10 with 2.2.3 version
> Fixing file
> 
> C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini
> 
> and set
> 
> udp_start_port_range = 20000
> udp_end_port_range = 30000
> 
> resolve this issue i think on windows config must be changed by default!

This didn't work for me.

**Comment by vasiliyaltunin** [comment] 2020-01-04 04:37
> > I have same issue on windows 10 with 2.2.3 version
> > Fixing file
> > C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini
> > and set
> > udp_start_port_range = 20000
> > udp_end_port_range = 30000
> > resolve this issue i think on windows config must be changed by default!
> 
> This didn't work for me.

You may need reboot after this changes.

**Comment by bsweeney83** [comment] 2020-01-04 05:43
> > > I have same issue on windows 10 with 2.2.3 version
> > > Fixing file
> > > C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini
> > > and set
> > > udp_start_port_range = 20000
> > > udp_end_port_range = 30000
> > > resolve this issue i think on windows config must be changed by default!
> > 
> > 
> > This didn't work for me.
> 
> You may need reboot after this changes.

Good call. I reinstalled Geforce Experience and then rebooted, and can now open projects without a problem. Thanks!

**Comment by fred-cardoso** [comment] 2020-01-09 00:03
I can also vouch for this solution. @vasiliyaltunin solution seems to be the way to go.

**Comment by techcanbefun** [comment] 2020-01-11 01:09
I can confirm uninstall "NVIDIA GeForce Experience" fixed my issue of opening GNS3 projects. Thank you everyone.

**Comment by Goose153** [comment] 2020-01-25 01:43
> I have same issue on windows 10 with 2.2.3 version
> Fixing file
> 
> C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini
> 
> and set
> 
> udp_start_port_range = 20000
> udp_end_port_range = 30000
> 
> resolve this issue i think on windows config must be changed by default!

This fixed the issue for me also.
Thank you!

**Comment by grossmj** [comment] 2020-01-25 08:50
The UDP port range has been changed to 20000-30000 since GNS3 version 2.2.3. As explained above, the 2 ways to solve the issue are:

* To edit the server config located in `C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini` by default and set `udp_start_port_range = 20000` + `udp_end_port_range = 30000`
* Uninstall "NVIDIA GeForce Experience" which conflicts with GNS3.

**Closed by grossmj** 2020-01-25 08:50 UTC

**Comment by chunji08** [comment] 2020-03-04 21:29
I had the exactly the same problem.  My GNS3 of version 2.1.9 is installed on window 10, and both GNS3 main server and remote servers are on a bunch of ubuntu VM. What I don't understand is I was not able to open some projects, but the rest are OK. The difference from project to project, are they are on the different remote server ? So what could be the fix for my case ? 

The reason I didn't update to the latest GNS3 is , the GNS3 not backward compatible.  If I had the newer one installed, it could not even detect my old projects.

**Comment by PierreYnov** [comment] 2020-04-16 11:23
> 
> 
> > > > I have same issue on windows 10 with 2.2.3 version
> > > > Fixing file
> > > > C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini
> > > > and set
> > > > udp_start_port_range = 20000
> > > > udp_end_port_range = 30000
> > > > resolve this issue i think on windows config must be changed by default!
> > > 
> > > 
> > > This didn't work for me.
> > 
> > 
> > You may need reboot after this changes.
> 
> Good call. I reinstalled Geforce Experience and then rebooted, and can now open projects without a problem. Thanks!

Same, thanks

**Comment by Neanding** [comment] 2020-05-17 00:24
thank you so much!! :)

**Comment by b-codex** [comment] 2021-08-12 14:17
Solution : change the default UDP port range to be 20000 - 30000.

**Comment by b-codex** [comment] 2022-01-24 19:21
for me changing the port worked. i dont really know what is causing it besides the port collision with NVIDIA experience.
maybe share ur screenshot here...?

**Comment by chathuraamal** [comment] 2022-01-25 15:58
> for me changing the port worked. i dont really know what is causing it besides the port collision with NVIDIA experience. maybe share ur screenshot here...?

thanks for the reply b-codex
posted some screencaps as you've suggested.
I've tried several udp port ranges (2k-3k, 10k- 20k, 20k-30k) but can't seem to identify what is causing the problem.
I don't have nvidia experience installed (I only have the gpu drivers installed) and tried with AV turned off (eset)

![image](https://user-images.githubusercontent.com/15794798/151011921-f8072441-c84f-4cba-8a8d-19dc2ef94a9d.png)
![image](https://user-images.githubusercontent.com/15794798/151011998-77a7b379-4d63-4c44-a143-8ee61ce46677.png)

**Comment by MrEdd01** [comment] 2023-06-09 11:24
> Today I had the same problem, I tried all the solutions proposed on different site, none worked ... Reinstalling GN3 with and without restarting the computer, removing gns3 registry keys and more. I finally found the solution and I want to share it because I think it will help somebody. I found the solution with a stroke of luck, it came from the software **nvidia Geforce Experience**, because when I did not have it I could open my projects, but once installed I could not do it anymore, I did the test several times and **the problem comes from the GeForce Experience software**. I hope this will help some person.

Thanks a LOT

**Comment by sola-law** [comment] 2024-08-19 05:28
> The UDP port range has been changed to 20000-30000 since GNS3 version 2.2.3. As explained above, the 2 ways to solve the issue are:
> 
> * To edit the server config located in `C:\Users\user\AppData\Roaming\GNS3\2.2\gns3_server.ini` by default and set `udp_start_port_range = 20000` + `udp_end_port_range = 30000`
> * Uninstall "NVIDIA GeForce Experience" which conflicts with GNS3.

Uninstalling NVIDIA GeForce Experience worked for me..Thanks!!
