### ISSUE TITLE
GNS3 2.2.9 RequestsDependencyWarning

### ISSUE THREAD

**Issue by PiAil** [GNS3/gns3-server#1773] opened 2020-06-04 15:46 UTC
Hello,

I'm not sure if this is a GNS3 bug (it looks like a `requests` package bug more), but after the last update, I have this warning after each command (`gns3server -v` for instance).

`/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)` .

I guess I could try to update the dependencies, but I'm not sure.

**Versions**

OS        Ubuntu 18.04
GNS3    2.2.9 (installed from repository, updated from 2.2.8)
Python  3.6.9
requests 2.18.4
urllib3   1.22 (this, indeed, does not look correct)
chardet 3.0.4

**Comment by grossmj** [comment] 2020-06-04 15:51
Thanks, I am going to investigate.

**Comment by grossmj** [comment] 2020-06-06 08:59
This is very strange because GNS3 server doesn't use requests. Also, I downgraded to urllib3 1.22 but didn't see any error message.

```
$ python3 -m pip freeze | grep urllib3
urllib3==1.22
$ python3 -m pip freeze | grep requests
requests==2.22.0
```

**Comment by PiAil** [comment] 2020-06-06 10:11
I just tried on a clean install (vagrant box `ubuntu/bionic64`), and I have the same warning.

Just `vagrant init ubuntu/bionic64`, `vagrant up`, `vagrant ssh`, and in the VM:
```
sudo add-apt-repository ppa:gns3/ppa -y
sudo apt-get update
sudo apt-get install gns3-gui gns3-server -y
gns3server -v
```

**Comment by grossmj** [comment] 2020-06-06 11:43
Maybe this is because we created the last Debian package without dh-virtualenv.

Can you try to install from our unstable PPA? This package has been created using dh-virtualenv, thanks :)

```
sudo add-apt-repository ppa:gns3/unstable -y
sudo apt-get update
sudo apt-get install gns3-gui gns3-server -y
gns3server -v
```

**Comment by grossmj** [comment] 2020-06-06 11:51
Ooppss sorry, disregard the previous answer. I forgot you are on Ubuntu Bionic, not Focal. The Bionic package is built using dh-virtualenv.

**Comment by cioby23** [comment] 2020-06-06 12:09
I just deployed for testing a Ubuntu bionic vagrant box and indeed the warning is displayed. The issues appears to be that python-requests package. If I remove it warning dissappears.

On the python-requests Github page the setup.py includes these requirements
https://github.com/psf/requests/blob/master/setup.py#L44

requires = [
    **'chardet>=3.0.2,<4',**
    'idna>=2.5,<3',
    'urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1',
    'certifi>=2017.4.17'

It seems python3-chardet package version 3.0.4 which is provided by Ubuntu does not meet their requirements. So this issue is not GNS3 related.

**Comment by grossmj** [comment] 2020-06-06 13:49
Thanks @cioby23 :+1: I couldn't get the same results using Docker with the ubuntu:20.04 image.

**Comment by grossmj** [comment] 2020-06-07 02:41
I am going to close this since the problem is outside GNS3. @PiAil please post back if you see any other issue. Thanks guys :+1:

**Closed by grossmj** 2020-06-07 02:41 UTC
