### ISSUE TITLE
Unable to upload qcow2 images onto Ubuntu 16 GNS3 remote server

### ISSUE THREAD

**Issue by yfquek** [GNS3/gns3-server#1431] opened 2018-10-22 07:13 UTC
Remote GNS3 server with Ubuntu 16 is working fine with regular Cisco images. But while I try to upload Juniper vSRX qcow2 image onto the GNS3 server, the following error occurs.
![image](https://user-images.githubusercontent.com/20177737/47281196-678c4e00-d60c-11e8-82fe-a504f4bdcbdf.png)

Running Juniper vSRX qcow2 image on local server was not a problem, but when it comes to Ubuntu 16 remote server, the upload fails.
I have tried uploading other images such as Cisco IOU and real IOS which supports Dynamips without any issues.

**Comment by grossmj** [comment] 2018-10-27 13:08
Duplicate of https://github.com/GNS3/gns3-server/issues/1432

**Closed by grossmj** 2018-10-27 13:08 UTC
Labels: Duplicate
