### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by JampyVi98** [GNS3/gns3-server#1928] opened 2021-07-02 03:29 UTC
Hello, spanish speaker here. I'm trying to start the routers on my topology but it gives me this error.

=> Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605

I'm using this image c7200-adventerprisek9-mz.150-1.M.image and I've been using it a long time. GNS3 wasn't opening, so I removed it and reinstalled. Now, GNS3 is working but Dynamips isn't responding.

NEOFETCH
OS: Pop!_OS 21.04 x86_64
Host: 80XL Lenovo ideapad 320-15IKB
Kernel: 5.11.0-7620-generic
Uptime: 46 mins
Packages: 2502 (dpkg), 20 (flatpak)
Shell: zsh 5.8
Resolution: 1920x1080, 1366x768
DE: GNOME 3.38.4
WM: Mutter
WM Theme: Pop
Theme: Pop-dark [GTK2/3]
Icons: Pop [GTK2/3]
Terminal: x-terminal-emul
CPU: Intel i7-7500U (4) @ 3.500GHz
GPU: NVIDIA GeForce 940MX
GPU: Intel HD Graphics 620
Memory: 3363MiB / 15787MiB

I've already tried reinstalling dynamips and it hasn't worked. Please help.
![image](https://user-images.githubusercontent.com/47112909/124216369-bed06500-dabb-11eb-80d3-e722529b6b55.png)

I forgot to mention that the version of GNS3 is 2.2.22

**Comment by grossmj** [comment] 2021-08-23 04:29
How have you installed Dynamips?

I have no issues running this IOS image with Dynamips version 0.2.21 on Ubuntu Focal

```
$ dynamips 
Cisco Router Simulation Platform (version 0.2.21-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Jul 12 2019 11:00:00

Please specify an IOS image filename
Usage: dynamips [options] <ios_image>
<...>
```

```
$ dynamips -P 7200 c7200-advipservicesk9-mz.150-1.M.bin
Cisco Router Simulation Platform (version 0.2.21-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Jul 12 2019 11:00:00

IOS image file: c7200-advipservicesk9-mz.150-1.M.bin
<...>
```

**Comment by grossmj** [comment] 2021-09-20 08:41
Duplicate of https://github.com/GNS3/gns3-server/issues/1363

**Closed by grossmj** 2021-09-20 08:41 UTC
Labels: Duplicate
