### ISSUE TITLE
Openning the same project multiple times creates problems

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#81] opened 2015-03-02 04:59 UTC
Steps to reproduce:

Start a GUI and load a project.
Start a second GUI and load the same project
At this point error messages like these can been seen (expected):

```
Response error: Error downloading http://127.0.0.1:8000/v1/projects/89bb17b3-de47-4dba-bdac-35e1d09b4ef9/dynamips/vms - server replied: Conflict
error while setting up R1: TCP port 2001 already in use on host
Server error from 127.0.0.1:8000: R1: TCP port 2001 already in use on host
Response error: Error downloading http://127.0.0.1:8000/v1/projects/89bb17b3-de47-4dba-bdac-35e1d09b4ef9/dynamips/vms - server replied: Conflict
error while setting up R2: TCP port 2002 already in use on host
Server error from 127.0.0.1:8000: R2: TCP port 2002 already in use on host
Response error: Error downloading http://127.0.0.1:8000/v1/projects/89bb17b3-de47-4dba-bdac-35e1d09b4ef9/dynamips/vms - server replied: Conflict
error while setting up R3: TCP port 2003 already in use on host
Server error from 127.0.0.1:8000: R3: TCP port 2003 already in use on host
FR1 has been created
```

Close the second GUI.
Close the first GUI.

Errors like these can be seen and we cannot close the GUI (similar to bug https://github.com/GNS3/gns3-server/issues/80)

```
Response error: Error downloading http://127.0.0.1:8000/v1/projects/89bb17b3-de47-4dba-bdac-35e1d09b4ef9/close - server replied: Not Found
Error while closing project 89bb17b3-de47-4dba-bdac-35e1d09b4ef9: Project ID 89bb17b3-de47-4dba-bdac-35e1d09b4ef9 doesn't exist
```

Proposed solution: when loading a topology we should try to create the project just once. This can be implemented in the createNode() method of each module class (e.g. https://github.com/GNS3/gns3-gui/blob/rest-api/gns3/modules/vpcs/__init__.py#L167) like it was done in the old GUI. This should be combined with a server version check.

On the server side in project manager we send an error if the project is already openned: 
https://github.com/GNS3/gns3-server/blob/asyncio/gns3server/modules/project_manager.py#L73

**Comment by noplay** [comment] 2015-03-02 07:56
I see two issues:
* I can't recreate the same vm twice due to a port issue. We should not raise an error if it's the same VM use the same port (not necessary for this use case, but more generaly that doesn't sound a valid error)
* If I have two gui open when i close one the project is closed for all the clients. The problem is we don't know if others clients are connected to the servers, before closing a project.

**Comment by noplay** [comment] 2015-03-02 14:37
I have fix the issues related for the double open

**Comment by noplay** [comment] 2015-03-02 14:44
About the close issue. What did you think about preventing close of a project if a a client listen the notification feed?

**Comment by noplay** [comment] 2015-03-02 14:50
We need to discuss the reopening project by phone i think we have some corner cases ...

**Comment by noplay** [comment] 2015-06-12 11:33
Tested it's work fine with the notification feed. The system checking if another client is not connected work.

**Closed by noplay** 2015-06-12 11:33 UTC
Labels: bug, enhancement
