### ISSUE TITLE
No data returned from 127.0.0.1:51477, uBridge process running: True

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1289] opened 2018-02-08 23:55 UTC
From GNS3 community forum:
https://gns3.com/discussions/ubridge-process-running-true

----------------------

Hi
Opening GNS3'project (2.1.0, Win10 x64)  after one month i see suddenly this stupid error:
 
No data returned from 127.0.0.1:51477, uBridge process running: True
 
What is that ? I'm not able to open my project because of that.

----------------------

Noticed prior tickets with the same errors:
https://github.com/GNS3/gns3-server/issues/275
https://github.com/GNS3/gns3-server/issues/976

**Comment by grossmj** [comment] 2018-02-09 07:00
We need to check the output of uBridge. The log file is ubridge.log and there is one file for each node.

**Comment by grossmj** [comment] 2018-03-07 12:43
This should fix the problem.

**Comment by abner19** [comment] 2018-03-20 05:06
Hello, where can I find the solution for this..?

Thanks,
Rick

**Comment by grossmj** [comment] 2018-03-20 05:07
@abner19 please download and install GNS3 version 2.1.4

**Comment by abner19** [comment] 2018-03-20 05:09
Hi, I'm running ver 2.1.4.. Win 10

**Comment by grossmj** [comment] 2018-03-20 05:11
Can you reproduce the issue every time?

**Comment by abner19** [comment] 2018-03-20 05:13
Thanks for the swift response. Started working after the 5th try or so, beats me...

**Comment by grossmj** [comment] 2018-04-16 08:42
This time I found the source of the problem. Should be good now.

**Comment by retralE** [comment] 2018-04-21 18:59
I find this problem is not fixed.  I've got 4 MikrotikCHR's hooked together and when I try to put NAT to one of them I get Error while creating node: No data returned from 127.0.0.1:55459, uBridge process running: True
Error while creating node: No data returned from 127.0.0.1:55466, uBridge process running: True
Until I've tried about 5 times then it works.  It's almost as if it's trying ports that are not working because every error has a randomized port and eventually one works.

**Comment by grossmj** [comment] 2018-04-24 09:49
Do you get the error when you try to link one of your Mikrotik node to a NAT cloud? Please post some screenshots if you can.

Thanks,

**Comment by retralE** [comment] 2018-04-27 20:52
Sorry for the wait I was away from networking the last few days.  For whatever reason it works every time I’ve tried it today.  When it was happening it would do it on both the NAT and Cloud, but only when I select my Desktop as the server and not GNS-VM.

Sent from Mail for Windows 10

**Comment by grossmj** [comment] 2018-04-28 11:27
Thanks for the feedback. Was it happening when you dropped the NAT or Cloud node in the drawing area?

**Comment by retralE** [comment] 2018-04-28 15:59
It would happen when I dropped the cloud or nat in the draw area and had selected Desktop-"mydesktop" for the server and hit ok.
It would never do it when selecting the gns3vm for a server though.

⁣Sent from BlueMail ​

**Comment by grossmj** [comment] 2018-06-12 08:01
I am suspecting an issue with uBridge 0.9.13. I have added version 0.9.12 for the next release which will help troubleshoot this.

**Comment by sixshakybones** [comment] 2018-08-17 15:52
Hi, I am getting the same error message.

- Windows10 home X64 with VirtualBox 5.2.16
- GNS3 2.1.9
- Ubridge 0.9.12
- IOU L2 and L3 appliance added

Create a new project. Drag appliances and link. Try to start first VM and error pops up. Sometimes I am able to start the first VM with no error and the second VM will cause an error.

![image](https://user-images.githubusercontent.com/41612180/44275651-64fd2900-a256-11e8-9d26-cdd3c57d7121.png)

IOU VM works just fine. am able to boot both L2 and L3 appliances and enter console. VirtualBox VM works fine too when starting them in GNS. Although the error pops up I am unable to perform and network activity between the host VM's

Ubridge log shows :
uBridge version 0.9.13 running with WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Hypervisor TCP control server started (IP 192.168.56.1 port 50431).
hypervisor_tcp_server: unable to create new connection for FD 4

Wondering if there is a fix for this yet ?

Thanks

**Comment by grossmj** [comment] 2018-08-21 11:00
> uBridge version 0.9.13 running with WinPcap version 4.1.3 (packet.dll version 4.1.0.2980)

Do you have the same issue with uBridge version 0.9.12? You can find uBridge 0.9.12 in the GNS3 install directory. Just change the uBridge path in the preferences and restart GNS3.

Thanks!

**Comment by grossmj** [comment] 2018-08-24 10:03
@sixshakybones ping, thanks :)

**Comment by sixshakybones** [comment] 2018-09-02 14:36
Apologies for my late response. I have tried that suggestion and I face the same issue still.

**Comment by grossmj** [comment] 2018-09-02 14:44
@sixshakybones Thanks for your help. This bug is really hard to squash. Please can you try the following development version and let me know the outcome: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-09-02/2.1/GNS3-2.1.2018-09-02-all-in-one.exe/download

Thanks!

**Comment by sixshakybones** [comment] 2018-09-08 12:58
Hi,

Same thing unfortunately.

![gns3](https://user-images.githubusercontent.com/41612180/45254390-4cc98700-b388-11e8-8a99-08ebae1b7c87.png)

**Comment by sixshakybones** [comment] 2018-09-25 09:56
@grossmj have you any further news on this ?

**Comment by grossmj** [comment] 2018-09-25 09:58
@sixshakybones version 2.1.10 may have fixed this problem. Can you confirm this since we cannot reproduce that issue on our side?

Thanks! :)

**Comment by sixshakybones** [comment] 2018-09-25 10:13
Thanks, I have tried that. Good news is I haven't got the message bad news is I got this message.
A quick google search does not bring up any results.

Error while creating node: GNS3 controller version 2.1.10 is not the same as compute server GNS3 VM (GNS3 VM) version 2.1.9

**Comment by grossmj** [comment] 2018-09-25 10:42
Oh this means you must upgrade the GNS3 VM to version 2.1.10 (upgrade entry
in the menu).

**Comment by sixshakybones** [comment] 2018-09-25 11:18
PERFECT !!! Its working, You have made me so happy, thanks for all your development efforts !

I did get one error message popup but it does not seem to have affected the VM startup.
When starting the first virtual machine this error comes up : Could not determine uBridge version for C:\Program Files\GNS3\ubridge.EXE

**Comment by grossmj** [comment] 2018-09-25 21:10
@sixshakybones do you get this error message everytime?

**Comment by sixshakybones** [comment] 2018-09-26 11:48
@grossmj I have tested, yes it does. It happens each time starting a virtual machine, 3 times if I have 3 VM's. They all start however.

> error while starting Win7ProX86-Attacker-1: No data returned from 127.0.0.1:62989 after sending command 'hypervisor version
', uBridge process running: True
> error while starting Server2012R2-1: No data returned from 127.0.0.1:63009 after sending command 'hypervisor version
', uBridge process running: True

e

I cant add a cloud to the network using the host system as the option from the menu provided once the cloud is dragged into the project. 

Error: No data returned from 127.0.0.1:63009 after sending command 'hypervisor version
', uBridge process running: True

**Comment by grossmj** [comment] 2018-10-03 12:58
@sixshakybones I can't figure out what is the problem. Would you mind if I take remote control of your computer using Team Viewer so I can debug that issue? Please contact me on developers@gns3.net to discuss a time and exchange information.

Thanks!

**Comment by sixshakybones** [comment] 2018-11-27 17:06
You are more than welcome to connect again and install whatever you want and runn whatever you need

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by grossmj** [comment] 2018-12-04 19:36
Please can you try this development build to see if it changes anything?

https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-12-04/2.1/GNS3-2.1.2018-12-04-all-in-one.exe/download

Thanks!

**Comment by sixshakybones** [comment] 2018-12-05 14:41
Yo,

Sure, I will give it a go on Friday and get back to you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sixshakybones** [comment] 2018-12-19 15:55
Sorry for the late response. Im still getting an error for ubridge. All VM start though

On 04 Dec 2018 11:36 PM, Jeremy Grossmann <notifications@github.com> wrote:

Please can you try this development build to see if it changes anything?

https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-12-04/2.1/GNS3-2.1.2018-12-04-all-in-one.exe/download

Thanks!

**Comment by byunkook** [comment] 2019-02-16 01:48
Looks like this is still an on-going issue. I do have the same issue on the lastest version 2.1.12.

**Comment by grossmj** [comment] 2019-02-16 02:39
@byunkook do you confirm this happens only with VirtualBox and VMware nodes?

**Comment by byunkook** [comment] 2019-02-16 02:54
I'm using VMs in VMware and this is only happening to VM nodes.
This is the exact error message 
No data returned from 127.0.0.1:54925 after sending command 'hypervisor version' uBrdige process running:True

I use vmware for GNS3 VM.

When I tried to start a VirtualBox VM node,  I get the following error.
"error while starting macOS-1: Cannot start VM because hardware virtualization (VT-x/AMD-V) is already used by another software like VMware or KVM (on Linux)

 I never tried GNS3 with VirtualBox GNS3 VM and a VirtualBox node.

**Comment by byunkook** [comment] 2019-02-16 04:37
FYI, uninstalling VirtualBox fixed the issue. 
I no longer get error messages on VMware nodes

I don't understand why installing VirtualBox would interfere and trigger such error on VMware VMs in GNS3 project. I didn't run it. It wasn't running in the background either.

**Comment by grossmj** [comment] 2019-02-27 12:24
Please can you try version 2.1.14 to check if the problem is still present? Thanks :)

**Comment by sixshakybones** [comment] 2019-02-28 11:26
Will do, Will update you next week

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by byunkook** [comment] 2019-03-02 13:51
It's better now. I don't get those reported error messages when I start VMware and Virtualbox VM.

Here's new one from .14. 
If Virtualbox VM in the project is running on the host already, and if you choose the project to launch, I get below error.

=> VirtualBox has returned an error: 

Once I stop the Virtualbox VM, then I can open the project.
With VMware VM, GNS3 doesn't behave this way, it doesn't care if VMware VM in project is running standalone.

Thank you

**Closed** 2019-03-31 04:36 UTC
Labels: Bug
