### ISSUE TITLE
[ 2.0 RC2] xml.etree.ElementTree.ParseError: not well-formed

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#952] opened 2017-03-20 09:00 UTC
Updated to 2.0 RC2, when opening a file created under 1.5.3, it crashes:

> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/http_client.py", line 612, in _processResponse
>     callback(params, server=server, context=context, raw_body=raw_body)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/project.py", line 401, in _listDrawingsCallback
>     topo.createDrawing(drawing)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/topology.py", line 536, in createDrawing
>     svg = ET.fromstring(drawing_data["svg"])
>   File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
>     parser.feed(text)
>   File "<string>", line None
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 20
>

**Comment by noplay** [comment] 2017-03-20 09:12
Duplicate of https://github.com/GNS3/gns3-gui/issues/1946

**Comment by noplay** [comment] 2017-03-20 09:13
Could you share the project directory?

**Comment by AJNOURI** [comment] 2017-03-20 16:22
Do you mean content list or the content itself ?

ajn@~/GNS3/projects/vpn1$` ls -la`

> total 180
> drwxr-xr-x   3 ajn ajn   4096 Mar 20 09:57 .
> drwxr-xr-x 131 ajn ajn   4096 Mar 19 09:09 ..
> drwxr-xr-x   7 ajn ajn   4096 Mar 20 09:44 project-files
> -rw-r--r--   1 ajn ajn 100098 Mar 20 09:33 screenshot.png
> -rw-r--r--   1 ajn ajn  38403 Mar 20 09:57 vpn1.gns3
> -rw-r--r--   1 ajn ajn  25170 Mar 20 09:43 vpn1.gns3.backup4
>

**Comment by noplay** [comment] 2017-03-20 17:41
The content of the .gns3

**Comment by AJNOURI** [comment] 2017-03-20 17:45
Here you go:
[vpn1.zip](https://github.com/GNS3/gns3-server/files/855859/vpn1.zip)

**Comment by noplay** [comment] 2017-03-20 18:00
Thanks I found the issue you use  < in text  we don't correctly escape it.

**Comment by AJNOURI** [comment] 2017-03-20 18:09
I removed the signes "<" and ">" from the comments in the .gns3 file.
Now it opens. Until next update I'll avoid these signs from the comments.
Thanks a lot Julien.

**Comment by noplay** [comment] 2017-03-20 18:19
Should work now

**Closed by noplay** 2017-03-20 18:19 UTC
Labels: bug
