### ISSUE TITLE
Cloned VirtualBox VMs cannot be restored from projects.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#175] opened 2015-05-05 03:24 UTC
Restoring a project containing cloned VirtualBox VMs produce the following error:

```
error while setting up Linux Microcore 4.7.1-1: VirtualBox has returned an error: VBoxManage: error: Trying to open a VM config '/home/grossmj/GNS3/projects/test2/project-files/virtualbox/fa57c87a-5fe4-4974-8ef7-a0da16b9d404/Linux Microcore 4.7.1-1/Linux Microcore 4.7.1-1.vbox' which has the same UUID as an existing virtual machine
```

@ehlers do you have this issue as well?

**Comment by grossmj** [comment] 2015-05-05 03:33
Looks like that closing the inaccessible medium files triggered that issue... weird.

**Comment by ehlers** [comment] 2015-05-05 12:36
Haven't seen this error. I just tried to reproduce it, but failed. Everything works as expected. Before you implemented the VirtualBox media manager cleanup, I did it manually, without any problems. I'm trying only on Mac OS X 10.9.5 and VirtualBox 4.3.26.

Is it reproducible ? What steps ?

**Comment by grossmj** [comment] 2015-05-07 00:30
Here are the steps: open GNS3, drop a VirtualBox VM with the linked base option, then save the project, close GNS3 and re-open it.

**Comment by ehlers** [comment] 2015-05-07 08:23
OK, now I reproduce it (GNS3 dev, head = d21469a). I'm pretty confident, that the reason is this dreadful save-as function.

In the past I learned to never use the Save-As function or to save a temporary project, it was too buggy. Therefore I didn't test that way.

Now to your issue:

After dropping the VirtualBox VM, a .vbox and the linked clones are created in a temporary directory.
![vmm_before-save](https://cloud.githubusercontent.com/assets/896406/7510734/c48d99c6-f49f-11e4-931d-42961ae17861.png)

With the save function, all is copied into your permanent project directory and the temporary directory is deleted. But VirtualBox doesn't know that, it still looks into the temporary directory.
![vbox_after_save](https://cloud.githubusercontent.com/assets/896406/7510783/23b2552c-f4a0-11e4-8ebb-5868707ec251.png)
![vmm_after-save](https://cloud.githubusercontent.com/assets/896406/7510784/2607fb88-f4a0-11e4-87f0-eae5b1c0f770.png)

If you try to start the VM in GNS3, you will get an error
```
Server error from 192.168.1.11:8000: TinyCore-1: VirtualBox has returned an error: VBoxManage: error: Could not find a registered machine named 'TinyCore-1'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2611 of file VBoxManageInfo.cpp
```

When you close GNS3 the inaccessable snapshots are removed from the media manager. The inaccessable VirtualBox linked clone VM is still there, the normal deletion of this VM doesn't work.

When you now try to restore the project, GNS3 tries to recreate the VirtualBox linked clone VM and link it to the snapshots. But as the VirtualBox VM is still there, you get this duplicate UUID error. Even if this old VirtualBox linked clone VM is deleted, it won't work, as the snapshots are gone.

If you first create a new project, then drop the VirtualBox VM into it, all is fine.

**Comment by grossmj** [comment] 2015-05-13 22:47
Hum, I'll prevent users to use VirtualBox cloned VMs in temporary projects for now and see if I can tell VirtualBox to look in the directory I want in version 1.4

**Comment by grossmj** [comment] 2016-02-02 17:47
This is not a big issue for now, especially if we decide to have a default project instead of the current temporary projects system.

**Comment by noplay** [comment] 2016-02-02 18:05
Also clone is marked as experimental

**Closed** 2016-03-23 04:50 UTC
Labels: wontfix
