### ISSUE TITLE
How to Limit resources on GNS3 Server per GNS3 client ?

### ISSUE THREAD

**Issue by MinaGithuub** [GNS3/gns3-server#2067] opened 2022-05-18 20:47 UTC
If we have multiple GNS3 Clients connect to one GNS3 Server ,and we want to limit RAM resource for each GNS3 Client , how to do that ?

**Comment by grossmj** [comment] 2022-06-15 08:49
Duplicate of https://github.com/GNS3/gns3-gui/issues/3332

**Closed by grossmj** 2022-06-15 08:49 UTC
