### ISSUE TITLE
Dynamips initial startup-config deleted, when topology is saved before first start

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#316] opened 2015-09-21 14:11 UTC
GNS3 version 1.4.0beta2 on Darwin (64-bit) with Python 3.4.3 Qt 5.5.0.

When you drag a new dynamips router into a topology, the initial startup-config and private-config is copied into the project-files/dynamips/configs/ directory.

When you now save the topology, the GNS3 server wants to extract the configs from the NVRAM and save it to the startup-config/private-config. As the router has never been started, the NVRAM file doesn't exist. That leads to the deletion of the startup-config/private-config. Now the router will start without an initial config.

**Comment by grossmj** [comment] 2015-09-21 18:03
I cannot reproduce the problem on Linux with c37xx routers. @noplay can you check this?

**Comment by ehlers** [comment] 2015-09-21 18:23
If have just tested with debian, also with version 1.4.0beta2. You are correct, I also can't reproduce it with 3725 router. Then I recalled, that I did that on OS X with an EtherSwitch (3725 with NM-16ESW). I re-tested it on OS X with an ordinary 3725 router, and I didn't have that problem.

I then re-tested this on debian with the EtherSwitch router and I now have the same problem also on linux.

@grossmj , can you please re-test with an EtherSwitch router?

**Comment by ehlers** [comment] 2015-09-21 18:29
Found the difference, my ESW has no initial private config, while the 3725 router has. When I change the 3725 router to have no private initial config, I can reproduce it also with the router.

**Comment by ehlers** [comment] 2015-09-21 18:46
Forget my above comments.

The procedure to reproduce the problem is more complex:
- create a new project
- drag a router into the project
- delete this router
- again drag a router
- verify that GNS3/projects/<project>/project-files/dynamips/configs/ has the startup-config
- save topology
- verify that GNS3/projects/<project>/project-files/dynamips/configs/ has no longer the startup-config

**Comment by noplay** [comment] 2015-09-22 11:49
I confirm the issue with 1.4.0beta2

**Comment by noplay** [comment] 2015-09-22 11:59
The issue is the following:
* R1 is deleted but project is not committed
* A router is added we reuse the router id 1
* We commit the project, now the old router 1 is cleaned and removed his files

**Closed** 2015-09-22 12:40 UTC
Labels: bug

**Comment by grossmj** [comment] 2015-09-22 15:42
Should be added on unstable branch as well I think.
