### ISSUE TITLE
Error : request GET /qemu/capabilities and request GET /qemu/binaries

### ISSUE THREAD

**Issue by CarlsonHue** [GNS3/gns3-server#2131] opened 2022-10-19 15:21 UTC
Having issue when I tried on adding new template recently. Having same issue on MAC and Windows virtual box workstation. 
<img width="891" alt="Screenshot 2022-10-19 at 11 16 46 PM" src="https://user-images.githubusercontent.com/21008972/196733214-f473257e-9c38-46aa-bca9-c3b3f416114d.png">
<img width="1225" alt="Screenshot 2022-10-19 at 11 18 47 PM" src="https://user-images.githubusercontent.com/21008972/196733640-725d7237-0cf7-4ba1-a10d-e4dd345b48cc.png">

Gns3vm and local server connection is working fine. Gns3 vm is connecting to internet. Only think I suspect, the qemu/binaries directory not found on my VM. Can anyone explain to me how its works?
Thank you

**Comment by BK201Pai** [comment] 2022-11-25 20:47
Had the same problem, checked almost every single forum post or video about a related error (POST /projects).
That was not it.
In my case i had to open the GNS3 VM, send enter and check the LOGS and it showed (CRITICAL webserver missing /opt/gns3).
So i had to:
- Open Shell
- "sudo su"
- "mkdir /opt/gns3"
- "chown gns3:gns3 /opt/gns3"
- Reboot
It then instantly connected, i assume some script didn't age quite so well.

**Comment by grossmj** [comment] 2022-12-28 03:31
@CarlsonHue do you confirm? what version of GNS3 have you used? thanks.

**Comment by BK201Pai** [comment] 2022-12-28 17:50
Version 2.2.35.1.
You can confirm if the problem is the same by going to the Logs, nginx will report "permission denied".

**Comment by grossmj** [comment] 2023-01-18 03:43
> It then instantly connected, i assume some script didn't age quite so well.

How have you installed the GNS3 VM? `/opt/gns3` should be present on the second disk...

**Comment by BK201Pai** [comment] 2023-01-23 21:30
Downloaded the lastest VM and imported the file, not sure if you tried using the latest available image from the website but it happened twice.

I did not modify the VM before starting it up.

**Comment by grossmj** [comment] 2023-02-04 05:32
Have you used VMware Workstation or VirtualBox to import the VM?

**Comment by grossmj** [comment] 2023-05-23 08:15
Still wondering how this could have happened. The GNS3 server in the VM shouldn't have started and logs should have shown `/opt/gns3` is not accessible.

![Screenshot from 2023-05-23 16-13-11](https://github.com/GNS3/gns3-server/assets/4752614/8c39d35f-9ac6-46ba-9480-88d16b185798)

I am going to close this for now. Hopefully this won't happen again.

**Closed by grossmj** 2023-05-23 08:15 UTC
Labels: Bug, Waiting for more information
