### ISSUE TITLE
Two VirtualBox VMs can't start at once

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#190] opened 2015-05-17 11:07 UTC
GNS3 V1.3.3, OS Mac OS X V10.9.5, VirtualBox 4.3.28

See https://community.gns3.com/message/27540#27540

Topology:
![eos](https://cloud.githubusercontent.com/assets/896406/7670057/a3a06f84-fc94-11e4-9f7b-0fd1b29a48aa.png)

If I start all devices at once, one of the VirtualBox VMs doesn't start. It's reproducible, it happens all the time. They are not linked clones, just 2 "normal" VMs. When I start one VM, wait a few seconds and then start the rest, everything works fine.

The log shows:
```
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 INFO virtualbox_vm.pyc:188 VirtualBox VM 'vEOS2' [a6f7e4b6-d77d-4287-983a-5ba74be52c7d] started
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 ERROR route.pyc:150 VM error detected: <class 'gns3server.modules.virtualbox.virtualbox_error.VirtualBoxError'>
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: Traceback (most recent call last):
May 17 12:40:52 imac.lan GNS3[2574] <Notice>:   File "gns3server/web/route.pyc", line 140, in control_schema
May 17 12:40:52 imac.lan GNS3[2574] <Notice>:   File "gns3server/handlers/api/virtualbox_handler.pyc", line 193, in start
May 17 12:40:52 imac.lan GNS3[2574] <Notice>:   File "gns3server/modules/virtualbox/virtualbox_vm.pyc", line 187, in start
May 17 12:40:52 imac.lan GNS3[2574] <Notice>:   File "gns3server/modules/virtualbox/__init__.pyc", line 114, in execute
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: gns3server.modules.virtualbox.virtualbox_error.VirtualBoxError: VirtualBox has returned an error: 
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 INFO server.pyc:169 127.0.0.1 - - Sun, 17 May 2015 10:40:52 GMT "POST /v1/projects/effde697-b8c6-49e7-abde-93fbd0234d1f/virtualbox/vms/c5a9a8db-41f9-4074-904f-058f047365b5/start HTTP/1.1" 409 308 "-" "GNS3 QT Client v1.3.3"
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 INFO http_client.pyo:362 Response error: Error downloading http://192.168.1.10:8000/v1/projects/effde697-b8c6-49e7-abde-93fbd0234d1f/virtualbox/vms/c5a9a8db-41f9-4074-904f-058f047365b5/start - server replied: Conflict
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 ERROR vm.pyo:96 error while starting vEOS1: VirtualBox has returned an error: 
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 INFO server.pyc:169 127.0.0.1 - - Sun, 17 May 2015 10:40:52 GMT "POST /v1/projects/effde697-b8c6-49e7-abde-93fbd0234d1f/virtualbox/vms/a6f7e4b6-d77d-4287-983a-5ba74be52c7d/start HTTP/1.1" 204 203 "-" "GNS3 QT Client v1.3.3"
May 17 12:40:52 imac.lan GNS3[2574] <Notice>: 2015-05-17 12:40:52 INFO vm.pyo:99 vEOS2 has started
```

**Comment by ehlers** [comment] 2015-05-17 11:49
The VirtualBox logs tells something about failed to start the UDP tunnel server:

```
00:00:00.132793 UDPTunnel#0: sport=10004;dest=192.168.1.10;dport=10005
00:00:00.132933 UDPTunnel#1: sport=10006;dest=192.168.1.10;dport=10007
00:00:00.133053 UDPTunnel#2: sport=10008;dest=192.168.1.10;dport=10009
00:00:00.133170 UDPTunnel#3: sport=10010;dest=192.168.1.10;dport=10011
00:00:00.133197 VMSetError: /Users/vbox/tinderbox/4.3-mac-rel/src/VBox/Devices/Network/DrvUDPTunnel.cpp(556) int drvUDPTunnelConstruct(PDMDRVINS*, CFGMNODE*, uint32_t); rc=VERR_PDM_HIF_OPEN_FAILED
00:00:00.133211 VMSetError: UDPTunnel: Failed to start the UDP tunnel server
00:00:00.133236 VMSetError: /Users/vbox/tinderbox/4.3-mac-rel/src/VBox/Devices/Network/DevE1000.cpp(7709) int e1kR3Construct(PDMDEVINS*, int, CFGMNODE*); rc=VERR_PDM_HIF_OPEN_FAILED
00:00:00.133236 VMSetError: Failed to attach the network LUN
00:00:00.133236 PDM: Failed to construct 'e1000'/4! VERR_PDM_HIF_OPEN_FAILED (-2852) - Unable to open the host interface.
00:00:00.137635 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={8ab7c520-2442-4b66-8d74-4ff1e195d2b6} aComponent={Console} aText={UDPTunnel: Failed to start the UDP tunnel server (VERR_PDM_HIF_OPEN_FAILED).
00:00:00.137646 Failed to attach the network LUN (VERR_PDM_HIF_OPEN_FAILED)}, preserve=false
00:00:00.139414 Power up failed (vrc=VERR_PDM_HIF_OPEN_FAILED, rc=NS_ERROR_FAILURE (0X80004005))
```

In https://community.gns3.com/thread/8516 the same VirtualBox error was shown, when he starts using 4  connections. I don't know if both issues are connected.

**Comment by noplay** [comment] 2015-05-29 14:58
I don't have the same issue with MacOS 10.10 and VirtualBox 4.3.26 I try to upgrade VirtualBox

**Comment by noplay** [comment] 2015-05-29 15:03
Idem with 4.3.28 and the following topology
![capture d ecran 2015-05-29 a 17 02 16](https://cloud.githubusercontent.com/assets/345437/7885530/a7712e34-0624-11e5-953d-eccdb9c2ca7c.png)

**Comment by noplay** [comment] 2015-05-29 15:05
Work also for this:
![capture d ecran 2015-05-29 a 17 05 16](https://cloud.githubusercontent.com/assets/345437/7885574/ecfcdc1e-0624-11e5-8b28-26f801bacd48.png)

**Comment by ehlers** [comment] 2015-05-29 15:11
You have to configure more links. My topology works, if I remove PC4. My current assumption is, that you need at least 2 virtual box VMs with 4 active interfaces each.

**Comment by ehlers** [comment] 2015-05-29 15:14
And I had no problems with this topology:
![vbox-8udp](https://cloud.githubusercontent.com/assets/896406/7885750/04fb92a0-0626-11e5-93af-ef84e1022692.png)

So you need something similar to my topology

**Comment by noplay** [comment] 2015-05-29 15:35
Your vEOS are VirtualBoxes ? And the PC4 is a VPCS?

**Comment by ehlers** [comment] 2015-05-29 15:43
Yes, the vEOS are VirtualBox VMs. Currently I use the linked clone feature, but for the test I created two full clones and used them.
![veos-vbox](https://cloud.githubusercontent.com/assets/896406/7886342/bab66e82-0629-11e5-94bc-1b0bcece9c54.png)

The PC1 - PC4 are VPCS.

In https://community.gns3.com/message/27540#27540 the topology is attached (untitled.gns3)

**Comment by noplay** [comment] 2015-05-29 15:45
This work for me:
![capture d ecran 2015-05-29 a 17 44 00](https://cloud.githubusercontent.com/assets/345437/7886432/5818b91e-062a-11e5-8d60-5f7c677534f5.png)

I will look deeply in your topology

**Comment by noplay** [comment] 2015-05-29 15:55
This crash for me:
![capture d ecran 2015-05-29 a 17 55 36](https://cloud.githubusercontent.com/assets/345437/7886672/f301205a-062b-11e5-9ad2-b9e7c65e99ff.png)

**Comment by noplay** [comment] 2015-06-01 12:30
Could you test with:
http://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2015-06-01/GNS3-stable.2015-06-01.dmg/download

It should start vm one by one

**Comment by ehlers** [comment] 2015-06-01 13:58
No, that doesn't work, it looks like before. Well, not really exactly. Neither with 1.3.3 nor with the test version I could reproduce the error with 4 VPCS, I increased them to 6 VPCS. But then the error was exactly the same with both versions.

But I'm not sure, I have your changed version.

GNS3.app is actual:
```
/Users/behlers# ls -l /Volumes/GNS3/
total 8
lrwxr-xr-x  1 behlers  staff   13  1 Jun 14:17 Applications@ -> /Applications
drwxr-xr-x  3 behlers  staff  102  1 Jun 14:16 GNS3.app/
```

But the contents of GNS3.app/Contents/Resources/lib/python34.zip is from today 05:16, but that may be because the time zone is not in the zip file.
```
/Users/behlers# unzip -l /Volumes/GNS3/GNS3.app/Contents/Resources/lib/python34.zip 
Archive:  /Volumes/GNS3/GNS3.app/Contents/Resources/lib/python34.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  06-01-15 05:16   ./
     4138  06-01-15 05:16   __future__.pyo
      983  06-01-15 05:16   _bootlocale.pyo
    23916  06-01-15 05:16   _collections_abc.pyo
     4310  06-01-15 05:16   _compat_pickle.pyo
     4792  06-01-15 05:16   _dummy_thread.pyo
    10619  06-01-15 05:16   _osx_support.pyo
    15585  06-01-15 05:16   _strptime.pyo
...
```

Of course I didn't start the GNS3 from the dog, I copied it to /Applications.

**Comment by noplay** [comment] 2015-06-01 14:04
You can check the version in the about dialog or in the console at the bottom.

I have the feeling Vbox OSX is not very reliable with large number of adapter...

**Comment by ehlers** [comment] 2015-06-01 14:11
Sure, it's 1.3.4dev1, but that doesn't tell me, if it's from today, yesterday or what else.

I created a debug log this time (from the nightly build). Because it's quite big, it's a gist:
https://gist.github.com/ehlers/a969aa224bbf1e725cd8

For me it looks, as if both VM are started one by one.

The virtualbox log again says something about UDP tunnel server failure:
```
00:00:00.133926 UDPTunnel#0: sport=10014;dest=192.168.1.10;dport=10015
00:00:00.133972 VMSetError: /Users/vbox/tinderbox/4.3-mac-rel/src/VBox/Devices/Network/DrvUDPTunnel.cpp(556) int drvUDPTunnelConstruct(PDMDRVINS*, CFGMNODE*, uint32_t); rc=VERR_PDM_HIF_OPEN_FAILED
00:00:00.133985 VMSetError: UDPTunnel: Failed to start the UDP tunnel server
00:00:00.134016 VMSetError: /Users/vbox/tinderbox/4.3-mac-rel/src/VBox/Devices/Network/DevE1000.cpp(7709) int e1kR3Construct(PDMDEVINS*, int, CFGMNODE*); rc=VERR_PDM_HIF_OPEN_FAILED
00:00:00.134019 VMSetError: Failed to attach the network LUN
00:00:00.134029 PDM: Failed to construct 'e1000'/0! VERR_PDM_HIF_OPEN_FAILED (-2852) - Unable to open the host interface.
00:00:00.138494 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={8ab7c520-2442-4b66-8d74-4ff1e195d2b6} aComponent={Console} aText={UDPTunnel: Failed to start the UDP tunnel server (VERR_PDM_HIF_OPEN_FAILED).
00:00:00.138506 Failed to attach the network LUN (VERR_PDM_HIF_OPEN_FAILED)}, preserve=false
00:00:00.140379 Power up failed (vrc=VERR_PDM_HIF_OPEN_FAILED, rc=NS_ERROR_FAILURE (0X80004005))
```

**Comment by noplay** [comment] 2015-06-01 14:32
Jeremy do you have the same issue on Linux?

**Comment by ehlers** [comment] 2015-06-01 14:36
Sure, i'm not jeremy :-), is he following this issue ?

Anyway I created this whole issue, because someone had problems with virtualbox on windows 7, see https://community.gns3.com/thread/8516. So don't think it's OS X specific.

**Comment by noplay** [comment] 2015-06-01 14:40
Yeah jeremy watch everything :)

**Comment by ehlers** [comment] 2015-06-01 15:18
I just tried on my debian 8 (Jessie) with gns3 v1.3.3.

I copied the vdi file from OS X and created 2 vEOS vbox VMs, the same as in OS X. I then created a topology with 2 vEOS VMs and 12 VPCS ( 6 per vEOS). No problems.

But there are some differences:
- The startup of the virtual box VMs takes much longer on linux than on OS X, about 15 sec compared to perhaps 2 seconds. But it works on linux.
- i7 on linux, i5 on OS X
- vpcs 0.5b2 on linux, 0.6 on OS X

**Comment by noplay** [comment] 2015-06-01 15:40
I understand the issue :) It's related to VPCS. 

VPCS allocate an UDP port at source + 9 sometimes it's collide with VirtualBox

**Comment by grossmj** [comment] 2015-06-01 15:43
In GNS3 VPCS is started using -i1 which should prevent that to happen or maybe there is a problem there?

**Comment by noplay** [comment] 2015-06-01 15:44
The options is here, perhaps vpcs ignore it

**Comment by noplay** [comment] 2015-06-01 15:46
I confirm same issue with vpcs trunk version

**Comment by noplay** [comment] 2015-06-01 15:49
The issue is here:
https://sourceforge.net/p/vpcs/code/HEAD/tree/trunk/src/relay.c#l318

**Comment by noplay** [comment] 2015-06-01 15:56
I found a way to dirty patch it by turning off the relay mode.

**Comment by noplay** [comment] 2015-06-02 12:41
Fixed by a VPCS patch

**Closed by noplay** 2015-06-02 12:41 UTC
Labels: bug
