### ISSUE TITLE
GNS3-Server(2.1.14) for Multiple Users Issue

### ISSUE THREAD

**Issue by MuhammadBor** [GNS3/gns3-server#1589] opened 2019-04-27 08:02 UTC
I have the following scenario for a Lab in an Academic Environment,

- 10 Users(Students) connect to a remote main server on The University Network. There is no computational load on client side.
- The server actually is an Ubuntu 18 equipped with 10 GB of Ram and 8 Cores.
- Students make a scenario similar to attached photo. Each of users makes a distinct project.
- For an End devices we use an Ubuntu Docker which is a command-base End device (Without GUI) with few commands to run.
- For Routers we use c3725.

The problem here is, when all students(Users) connect to the server, some of users(For instance, 8 of 10) will not be able to work on their project due to witnessing "Operation TimeOut or Connection TimeOut". At the stage of happening Timeout the server machine still got resources, but The main Process of Gns3-server will get to 100% usage, and there is no way to work on project rather than restarting
 the GNS3 service.

 

Is there any suggestion for our scenario to work properly? Is there any problem with GNS3 when it comes to scaling for multiple users?

==============
![gns3](https://user-images.githubusercontent.com/42133604/56846755-2e4cd780-68e8-11e9-87e2-5217cd847b19.JPG)
==========
Operating System: Windows 10
GNS3 Software Version: GNS3 2.1.14

**Comment by stkac** [comment] 2019-05-09 15:45
Hi same issue here...

**Comment by grossmj** [comment] 2019-05-20 09:57
Things should work a better with GNS3 version 2.2 (we will release our first beta soon) however proper user management is one of our next major goal. Ref https://github.com/GNS3/gns3-server/issues/1337

I the meantime please post any feedback or ideas regarding this. Thanks.

**Comment by srieger1** [comment] 2019-09-04 20:16
We have similar problems using GNS3 in our network lab at Fulda University of Applied Sciences. Looking forward to see improvements regarding the user management in GNS3. However, if you like, you can take a look at the interim solution we developed that acts as a proxy in front of GNS3 backends: https://github.com/srieger1/gns3-proxy. We're also thinking about further extensions to use GNS3 in classroom/course environments, as, e.g., also available for VIRL or mininet.

**Comment by grossmj** [comment] 2020-11-02 08:14
Duplicate of https://github.com/GNS3/gns3-server/issues/1250

**Closed by grossmj** 2020-11-02 08:14 UTC
Labels: Duplicate, Question
