### ISSUE TITLE
Addition of project sandboxing capability in a multi-user environment

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-server#1881] opened 2021-04-01 00:28 UTC
[Enhancement]

Currently when a GNS3-server is operating with multiple users, the environment is one single project. The users accessing the server/cluster have access to the entire to the entire project. A Multi-user environment would ideally have the capacity to sandbox projects enabling a per-user access to the topology, but not eliminate the capability for multiple users to connect to the same project.

**Comment by k4kfh** [comment] 2021-04-05 22:27
This question has been asked many times before, and I think most recently I asked about it in December. The last I heard, this feature was coming in release 3.0, but I don't know how that is progressing. In any case, this is probably a duplicate of #1337

**Comment by grossmj** [comment] 2021-06-03 08:59
RBAC support has been added which solves this issue.

**Closed by grossmj** 2021-06-03 08:59 UTC
