### ISSUE TITLE
Error duplicating project with start all nodes setting

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-server#1041] opened 2017-05-18 19:25 UTC
2.0.1

When a project is set with the "Start all nodes when this project is opened" property, attempting to duplicate the closed project from the Project Library screen will fail.  The project nodes will start up while the project is being examined and the duplication will fail with "Error while duplicate project: Running topology could not be exported".

**Comment by noplay** [comment] 2017-05-23 14:13
Hi,

I'm not able to reproduce the issue. 

* I created a project
* I put a VPCS node
* I set auto_start setting
* I change to another project
* I wait
* Now the project is closed in the project library
* I ask for duplicate and it's work

**Comment by noplay** [comment] 2017-05-23 14:13
Do you have the problem with this simple test? Or it's more complex

**Comment by CapnCheapo** [comment] 2017-06-08 13:21
Hey Julien,  I am not able to reproduce this in 2.0.2.  Must be fixed?

**Comment by noplay** [comment] 2017-06-08 14:01
Probably a side effect of something else. Good news !

**Closed by noplay** 2017-06-08 14:01 UTC
Labels: Bug, Waiting for more information
