### ISSUE TITLE
Leftover project directory after deleting project with qemu device

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#866] opened 2017-01-14 13:16 UTC
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

* create new project
* add a qemu device for the GNS3VM
* start devices
* stop devices
* delete project

The deletion shows no error and the local project directory is deleted. But on the GNS3VM the project directory is still partially there.

Project directory on the GNS3VM before deletion:
```
gns3@gns3vm:~$ ls -lR /opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36
/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan 14 14:06 project-files

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan 14 14:06 qemu

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files/qemu:
total 4
drwxrwx--- 2 gns3 gns3 4096 Jan 14 14:07 6268eb54-d076-4a15-8d1b-6ab86bf1dd84

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files/qemu/6268eb54-d076-4a15-8d1b-6ab86bf1dd84:
total 200
-rw-r----- 1 gns3 gns3 196624 Jan 14 14:07 hda_disk.qcow2
-rw-rw---- 1 gns3 gns3    642 Jan 14 14:07 qemu.log
gns3@gns3vm:~$
```

Project directory on the GNS3VM after deletion:
```
gns3@gns3vm:~$ ls -lR /opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36
/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan 14 14:07 project-files

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan 14 14:07 qemu

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files/qemu:
total 4
drwxrwx--- 2 gns3 gns3 4096 Jan 14 14:07 6268eb54-d076-4a15-8d1b-6ab86bf1dd84

/opt/gns3/projects/0570cecd-05a9-408b-8a75-9bfd2e779e36/project-files/qemu/6268eb54-d076-4a15-8d1b-6ab86bf1dd84:
total 0
gns3@gns3vm:~$
```

**Comment by noplay** [comment] 2017-01-17 14:20
I don't reproduce the issue. How do you delete the project? From the project list?

Thanks

**Comment by ehlers** [comment] 2017-01-17 14:43
Normally I'm using my own GNS3VM version, but I just repeated it with the official GNS3VM and I have the issue as well. I verified it, it's commit bfb23ce7a3ba307ba6e57c856fe4f7b930c5c0e3 . The GNS3 GUI and server on my mac are also the latest ones.

The procedure a little bit more in detail:
* start GNS3 GUI and create a new (empty project)
* drop the MicroCore VM (linux-microcore-6.4.img) into the project
* use the "Start/Resume all nodes" icon to start it
* use the "Stop all nodes" icon to stop it
* use File / Delete project menu item to delete project

GNS3 asks for confirmation, then it closes/deletes the project without any error or warning message. On my GUI/host computer the project is indeed completely gone. But in the GNS3VM the project directory is still there.

When I don't start/stop the QEMU VM I don't have this issue, only when it was started at least once.

**Comment by cioby23** [comment] 2017-01-17 14:51
I'm experiencing a similar issue. I create a new project and add several nodes on the topology (tried qemu, iou, vpcs ) and then deleted all those nodes and close the project.
When I look inside the qemu, iou and vpcs folders inside project-files folder there are left-over empty folders (uuid names) from the nodes I just deleted.
Tested on Local server on Linux.

**Comment by noplay** [comment] 2017-01-17 18:25
I confirmed delete from the File menu leftover some files when the delete
from project list work even if the call it's the same. It's seem an issue
because in one case the project is opened and not opened for the other.

**Comment by noplay** [comment] 2017-01-17 18:48
Should be fixed by last commit. Thanks!

**Closed by noplay** 2017-01-17 18:48 UTC
Labels: bug, waiting for more informations

**Comment by ehlers** [comment] 2017-01-17 19:14
Yes, that fixed it. Good job.
