### ISSUE TITLE
on windows ,Gns3 1.4RC can`t stop vmware VM

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-server#360] opened 2015-11-14 03:55 UTC
in gns3 1.4RC  of windows platform , after start vmware any vm,,if i click stop buttion ,it will time out 60S !

**Comment by qianxideyu** [comment] 2015-11-15 06:33
system version is windows 10 enterprise ，software version is vmware workstation  12 pro！

**Comment by noplay** [comment] 2015-11-30 07:05
Thanks for the report

**Comment by grossmj** [comment] 2015-12-06 22:23
@qianxideyu can you post the path to one of the .vmx corresponding to one of your VM?

Thanks,

**Comment by grossmj** [comment] 2016-01-26 04:17
Duplicate of https://github.com/GNS3/gns3-gui/issues/922

**Closed by grossmj** 2016-01-26 04:17 UTC
Labels: bug
