### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1828] opened 2020-10-13 15:52 UTC
Ubuntu 20.10/Debian 11.0
gns3-server 2.2.15

On **Debian bullseye**:
```
================================================================== short test summary info ===================================================================
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmpon6bdfgt',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmplsy20lyr',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
FAILED tests/compute/dynamips/test_dynamips_manager.py::test_project_closed[pyloop] - FileExistsError: [Errno 17] File exists: '/tmp/pytest-of-actionmystiq...
FAILED tests/handlers/api/compute/test_project.py::test_close_project[pyloop] - AssertionError: assert False
================================================== 4 failed, 878 passed, 141 warnings in 125.28s (0:02:05) ===================================================
```
On **Ubuntu groovy**:
```
================================================================== short test summary info ===================================================================
FAILED tests/handlers/api/controller/test_node.py::test_get_and_post_with_nested_paths_normalization[pyloop] - AssertionError: expected call not found.
FAILED tests/handlers/api/compute/test_qemu.py::test_upload_image[pyloop] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-actionm...
FAILED tests/handlers/api/compute/test_project.py::test_close_project[pyloop] - AssertionError: assert False
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmpph626ngq',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmpd6rl_r3o',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
================================================== 5 failed, 877 passed, 141 warnings in 137.67s (0:02:17) ===================================================
```
Full logs:
[gns3-server_2.2.15-11_amd64_tests.log](https://github.com/GNS3/gns3-server/files/5372496/gns3-server_2.2.15-11_amd64_tests.log)
[gns3-server_2.2.15-20.10_amd64_tests.log](https://github.com/GNS3/gns3-server/files/5372497/gns3-server_2.2.15-20.10_amd64_tests.log)

**Comment by grossmj** [comment] 2020-10-27 09:42
Duplicate of https://github.com/GNS3/gns3-server/issues/1810

**Comment by grossmj** [comment] 2021-04-21 04:37
Tests in branch 3.0 should work well.

**Closed by grossmj** 2021-04-21 04:37 UTC
