### ISSUE TITLE
Filesystem-level snapshots

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-server#1661] opened 2019-10-03 18:35 UTC
Future improvement when web-UI will support and the features and OS-specific builds can be dropped: https://gns3.com/community/discussion/new-feature-snapshot-rollback-sc

**Comment by grossmj** [comment] 2019-10-30 08:19
Duplicate of https://github.com/GNS3/gns3-server/issues/1675

**Closed by grossmj** 2019-10-30 08:19 UTC
Labels: Duplicate, Enhancement
