### ISSUE TITLE
/tmp/gns3/bin/udhcpc not found on Network Automation appliance

### ISSUE THREAD

**Issue by KienHoSD** [GNS3/gns3-server#2436] opened 2024-11-03 10:54 UTC
After trying to get an IP from DHCP with network configuration, I still can not get an IP and I found out another problem after that is udhcpc not appear to be in the /tmp/gns3/bin folder. Thanks to everyone who try to help me with this problem.
``` bash
root@NetworkAutomation:~# find / -name "*udhcpc*"
/gns3/etc/udhcpc
/gns3/bin/udhcpc
root@NetworkAutomation:~# /gns3/bin/udhcpc
/gns3/bin/udhcpc: exec: line 15: /tmp/gns3/bin/udhcpc: not found
root@NetworkAutomation:~# ls /tmp/gns3/bin
linuxrc
```
OS: Debian 12 (Bookworm)
GNS3: version 2.50
GNS3 VM: version 2.50
VMware: Workstation 17 Pro

All the appliances have been updated.

**Comment by grossmj** [comment] 2024-11-04 05:29
Do you have this problem with other Docker images?

What is the content of this directory? `ls -la ~/.local/share/GNS3/docker/bin/`

**Comment by KienHoSD** [comment] 2024-11-04 06:51
``` bash
❯ ls -la ~/.local/share/GNS3/docker/bin/
total 1948
drwxr-xr-x 2 kienho kienho    4096 Nov  2 19:01 .
drwxr-xr-x 4 kienho kienho    4096 Nov  2 19:01 ..
-rwxr-xr-x 1 kienho kienho 1982256 Apr 24  2023 busybox
-rwxr-xr-x 1 kienho kienho     323 Nov  2 19:01 udhcpc
```
udhcpc does appear in my computer. But others docker images (UbuntuDockerGuest) also not have udhcpc in its /tmp/gns3/bin directory.
``` bash
root@UbuntuDockerGuest-1:~# ls /tmp/gns3/bin
linuxrc
```

> Do you have this problem with other Docker images?
> 
> What is the content of this directory? `ls -la ~/.local/share/GNS3/docker/bin/`

**Comment by grossmj** [comment] 2024-11-04 07:52
Looks like the problem is due to another issue: https://github.com/GNS3/gns3-server/issues/2431

This will be fixed in our next release. In the meantime, please edit `~/.local/share/GNS3/docker/init.sh` and change `busybox --list` to `busybox --list-full`

Let me know this solves the issue.

**Comment by KienHoSD** [comment] 2024-11-04 09:30
I did edit `~/.local/share/GNS3/docker/init.sh` and change `busybox --list-full` to `busybox --list` and now its working! Thanks you for the answer!

**Closed** 2024-11-04 11:16 UTC
Labels: Waiting for more information
