### ISSUE TITLE
[2.1.3] "Use as a linked base VM" option in QEMU VMs is not evaluated

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-server#1299] opened 2018-02-17 18:19 UTC
Hi Everyone,
***
_EDIT :_

_Seems that this happens for QEMU images that existed before the update to 2.1.3_
***

I noticed  a problem with QEMU VMs created disabling the option _**Use as a linked base VM**_

The issue is that the changes applied to the original VM are not saved, so practically it always create a linked base VM even when the option is disabled.

To give some reason behind this I can tell the following: 

to expedite some testing on some labs I needed to create a Windows 2008 VM with some updates and packages installed so next VMs would be ready making me save a lot of time, so I did what I were able to do in the past : 

- deploy a Win2008 VM with the option  _**Use as a linked base VM**_ disabled
- Launch it and modify what is needed (patches, updates, etc)
- close the VM and delete it
- modify the template and re enable _**Use as a linked base VM**_ 
- create a new linked VM

All the changes are not saved from the original modified VM, in previous versions of GNS3 server I were able to do that

This is the option I am referring to
![image](https://user-images.githubusercontent.com/26431888/36344212-382349dc-1417-11e8-9dfe-553f9a2a36df.png)

**Comment by jhonnyx82** [comment] 2018-02-17 18:24
UPDATE:

I can see that even with the option disabled, the disk file used cloned : 

I noticed that the option file points to the project and not the orignal qcow2 file:

_**file=/home/gns3/GNS3/projects/7cff53dc-1205-4b60-b302-08670a4497cb/project-files/qemu/6991f385-74d9-4238-af7f-ff672269f2fc/hda_disk.qcow2**_

`ps aux | grep Win_2008_R2
gns3      2715  139  0.1 2639608 58444 ?       Sl   18:20   0:02 /usr/bin/qemu-system-x86_64 -name Win_2008_R2-Ent-1 -m 2048M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/gns3/GNS3/projects/7cff53dc-1205-4b60-b302-08670a4497cb/project-files/qemu/6991f385-74d9-4238-af7f-ff672269f2fc/hda_disk.qcow2,if=ide,index=0,media=disk -vnc 0.0.0.0:3 -monitor tcp:127.0.0.1:50394,server,nowait -net none -device e1000,mac=00:97:cb:f2:fc:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10057,localaddr=127.0.0.1:10056 -nographic -usbdevice tablet`

**Comment by jhonnyx82** [comment] 2018-02-17 18:47
Additional info:

I created a VM from a template with **_Use as a linked base VM disabled_** and looking at the file it uses I can see that is referencing to a linked-base : 

qemu-img info /home/gns3/GNS3/projects/7cff53dc-1205-4b60-b302-08670a4497cb/project-files/qemu/eee97bb6-cf9d-4242-9b06-7b93af8c41dc/hda_disk.qcow2
image: /home/gns3/GNS3/projects/7cff53dc-1205-4b60-b302-08670a4497cb/project-files/qemu/eee97bb6-cf9d-4242-9b06-7b93af8c41dc/hda_disk.qcow2
file format: qcow2
virtual size: 39G (41943040000 bytes)
disk size: 772K
cluster_size: 65536
backing file: /home/gns3/GNS3/images/QEMU/Win2008R2_Ent-hda.qcow2
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false

**Comment by jhonnyx82** [comment] 2018-02-17 21:04
EDIT : 

Seems that this happens for QEMU images that existed before the update to 2.1.3

**Comment by ehlers** [comment] 2018-02-26 14:20
Seems to be a duplicate of issue https://github.com/GNS3/gns3-gui/issues/2413

**Comment by ziajka** [comment] 2018-02-26 14:26
Good point @ehlers. Closing this in favor of issue you mentioned.

**Closed by ziajka** 2018-02-26 14:26 UTC
Labels: Duplicate
