### ISSUE TITLE
Closing project on remote GUI creates traceback

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-server#87] opened 2015-03-05 04:22 UTC
When I closed out a project on the remote GUI, I got the following traceback on the server:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gns3_server-1.3.0alpha1-py3.4.egg/gns3server/modules/project.py", line 185, in module_working_directory
    os.makedirs(workdir, exist_ok=True)
  File "/usr/local/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/istgroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gns3_server-1.3.0alpha1-py3.4.egg/gns3server/modules/project.py", line 286, in _close_and_clean
    future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/site-packages/gns3_server-1.3.0alpha1-py3.4.egg/gns3server/modules/dynamips/nodes/router.py", line 344, in close
    yield from self.save_configs()
  File "/usr/local/lib/python3.4/site-packages/gns3_server-1.3.0alpha1-py3.4.egg/gns3server/modules/dynamips/nodes/router.py", line 1528, in save_configs
    module_workdir = self.project.module_working_directory(self.manager.module_name.lower())
  File "/usr/local/lib/python3.4/site-packages/gns3_server-1.3.0alpha1-py3.4.egg/gns3server/modules/project.py", line 187, in module_working_directory
    raise aiohttp.web.HTTPInternalServerError(text="Could not create module working directory: {}".format(e))
aiohttp.web.HTTPInternalServerError: Internal Server Error
```
The path ("/home/istgroup") that the server is trying to access is the homedir of the user running the remote GUI, and does not even exist on the OS where the server is running...

**Comment by noplay** [comment] 2015-03-05 16:20
Did you try to open a new topology or it's a blank project?

**Comment by wdennis** [comment] 2015-03-05 20:34
It was a new topology that I created after installing 1.3...

**Comment by noplay** [comment] 2015-03-06 14:10
I confirm something happen, because one time i got the same  error. But i didn't found a way to reproduce it. 

* Do you use only remote servers? 
* What type of modules are you using? Dynamips, IOU,Qemu, VPCS?

**Comment by wdennis** [comment] 2015-03-06 14:15
- only remote gns3-server
- no server.conf on server
- only using Dynamips (no other backends)

**Comment by noplay** [comment] 2015-03-06 14:23
Thanks

@grossmj can you try? I didn't have the issue on my side.

**Comment by grossmj** [comment] 2015-03-12 00:07
I was able to reproduce the problem, even if I did not get the exact same error I believe it is has been fixed in https://github.com/GNS3/gns3-gui/commit/1be5f9f7486d47af5a1abaccc701b278f74a120e

Please re-open if you face a similar issue in the beta version.

Thanks,

**Closed by grossmj** 2015-03-12 00:07 UTC
Labels: bug
