### ISSUE TITLE
[2.2.12] Some tests fail

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1810] opened 2020-08-13 07:48 UTC
Debian bullseye
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
Using --randomly-seed=1952489090
rootdir: git-gns3-server, inifile: pytest.ini
plugins: cov-2.10.0, pythonpath-0.7.3, randomly-3.4.1, timeout-1.4.1, aiohttp-0.3.0, flaky-3.7.0

```
python3.8 setup.py install
sudo -u ${user} -EH py.test -vv
```
leads to
```
================================================================== short test summary info ===================================================================
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start[pyloop] - AssertionError: assert ('/tmp/tmpg7vt779a',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\n '1',...
FAILED tests/compute/vpcs/test_vpcs_vm.py::test_start_0_6_1[pyloop] - AssertionError: assert ('/tmp/tmp2uaccdjw',\n '-p',\n '5001',\n '-m',\n '1',\n '-i',\...
FAILED tests/compute/dynamips/test_dynamips_manager.py::test_project_closed[pyloop] - FileExistsError: [Errno 17] File exists: '/tmp/tmpg3rcgqck/projects/a...
================================================== 3 failed, 879 passed, 141 warnings in 151.80s (0:02:31) ===================================================
```
Full log: 
[gns3-server_2.2.12-11.0_amd64_tests.log](https://github.com/GNS3/gns3-server/files/5067788/gns3-server_2.2.12-11.0_amd64_tests.log)

**Comment by grossmj** [comment] 2020-10-27 09:42
Duplicate of https://github.com/GNS3/gns3-server/issues/1828

**Closed by grossmj** 2020-10-27 09:42 UTC
