### ISSUE TITLE
GNS3 wont launch client software  2.2.16 on Mac Big Sur VMWare fusion 12.1.0

### ISSUE THREAD

**Issue by wonnelp** [GNS3/gns3-server#1845] opened 2020-11-27 21:36 UTC
GNS 3 2.2.16 client software will not load on Mac Book Pro after upgrading to Big Sur 
Model Name:	MacBook Pro
Model Identifier:	MacBookPro16,1
Processor Name:	8-Core Intel Core i9
Processor Speed:	2.3 GHz
Number of Processors:	1
Total Number of Cores:	8
L2 Cache (per Core):	256 KB
L3 Cache:	16 MB
Hyper-Threading Technology:	Enabled
Memory:	64 GB

**Comment by b-ehlers** [comment] 2020-11-28 10:27
Duplicate of https://github.com/GNS3/gns3-gui/issues/3037

**Closed** 2020-11-29 05:37 UTC
