### ISSUE TITLE
/gns3/init.sh: line 79: sleep: not found, /gns3/init.sh: line 79: grep: not found

### ISSUE THREAD

**Issue by jcox-dev-99** [GNS3/gns3-server#1823] opened 2020-09-27 20:52 UTC
Hello~

I'm getting the above errors when attempting to open any containers in GNS3.  When I start the container within the topology, when I open the console I get a continuous, alternating repeat of the the same two errors:

/gns3/init.sh: line 79: sleep: not found 
/gns3/init.sh: line 79: grep: not found

I'm using openSUSE Leap 15.2, gns3-server-2.2.14

For containers, I’ve tried Ubuntu:latest, and kalilinux/kali:latest.  I get the same results on both.

Thanks in advance for any help.

**Comment by jcox-dev-99** [comment] 2020-09-27 20:59
Python version is highest available in standard openSUSE repository, python 3.6.10

**Comment by Philibilly** [comment] 2020-10-01 15:36
I see the very same behavior for my docker containers on SLES 15.
I'm just guessing but I think the issue is somehow related to busybox as it should provide the base commands for the container?
(I have BusyBox v1.26.2 installed)

**Comment by sudhanpu** [comment] 2021-05-03 10:57
yes i'm also facing same issue. Can someone please help to resolve the issue

i even delete existing container and restart again, still same issue

**Comment by sudhanpu** [comment] 2021-05-03 11:00
@grossmj appreciate your help here.

**Comment by txutxifel** [comment] 2021-11-16 06:51
Hi, 
I had same problem. I fixed it installing gns3 from pip:
sudo pip install gns3-server --upgrade
sudo pip install gns3-gui --upgrade

Cheers!

**Comment by Philibilly** [comment] 2021-11-25 13:33
Just wanted to leave an update as well: I do not know what has changed but the issue is suddenly gone. I can only assume that docker patched itself or something similar. GNS3 is still running the same version as when the issue occured.

Docker version 20.10.9-ce, build 79ea9d308018
GNS3server 2.2.14
Python 2.7.18

**Comment by grossmj** [comment] 2022-08-28 10:04
Duplicate of https://github.com/GNS3/gns3-server/issues/2069

**Closed by grossmj** 2022-08-28 10:04 UTC
Labels: Bug, Duplicate
