### ISSUE TITLE
libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable

### ISSUE THREAD

**Issue by Zero3Dash** [GNS3/gns3-server#2402] opened 2024-07-15 09:27 UTC
This is an FYI

When attempting to upgrade from 2.2.48 to 2.2.48.1
Same issue as https://github.com/GNS3/gns3-server/issues/2398

I we able to resolve by running "sudo gns3restore" and have successfully upgraded to 2.2.48.1

-------------------------------------------------------------------------------------------------------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1757  100  1757    0     0  14056      0 --:--:-- --:--:-- --:--:-- 14056
+ set -e
+ export BRANCH=focal-stable
+ BRANCH=focal-stable
+ export UNSTABLE_APT=0
+ UNSTABLE_APT=0
+ export PYPI_GNS3SERVER_JSON_URL=https://pypi.org/pypi/gns3-server/json
+ PYPI_GNS3SERVER_JSON_URL=https://pypi.org/pypi/gns3-server/json
+ curl -Lk https://raw.githubusercontent.com/GNS3/gns3-vm/focal-stable/scripts/upgrade_vm.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1940  100  1940    0     0  23095      0 --:--:-- --:--:-- --:--:-- 22823
+ bash -x /tmp/upgrade_vm.sh
+ set -e
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ cd /tmp
+ sudo rm -Rf 'gns3-vm-*'
+ echo 'Download https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz'
Download https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz
+ curl -Lk https://github.com/GNS3/gns3-vm/archive/focal-stable.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  134k    0  134k    0     0   326k      0 --:--:-- --:--:-- --:--:--  326k
+ tar -xzf gns3vm.tar.gz
+ rm gns3vm.tar.gz
+ sudo fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock
+ cd gns3-vm-focal-stable/config
+ sudo -E bash -x install.sh
+ set -e
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ dpkg-reconfigure libc6
+ sudo -E apt-get -q --option Dpkg::Options::=--force-confold --allow-change-held-packages --assume-yes install libssl1.1
Reading package lists...
Building dependency tree...
Reading state information...
libssl1.1 is already the newest version (1.1.1f-1ubuntu2.22).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
++ dpkg --print-architecture
+ [[ amd64 == \a\r\m\6\4 ]]
+ cat
+ dpkg --add-architecture i386
+ cp release-upgrades /etc/update-manager/release-upgrades
+ chmod 644 /etc/update-manager/release-upgrades
+ chown root:root /etc/update-manager/release-upgrades
++ which add-apt-repository
+ [[ ! -n /usr/bin/add-apt-repository ]]
+ [[ 0 == \1 ]]
+ sudo -E add-apt-repository -y ppa:gns3/ppa
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:6 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Reading package lists... Done
+ add-apt-repository -y --remove ppa:gns3/unstable
+ curl -fsSL https://download.docker.com/linux/ubuntu/gpg
+ sudo apt-key add -
OK
++ dpkg --print-architecture
++ lsb_release -cs
+ sudo -E add-apt-repository -y 'deb [arch=amd64] https://download.docker.com/linux/ubuntu    focal    stable'
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Get:6 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [46.4 kB]
Hit:7 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Hit:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 104 kB in 1s (124 kB/s)
Reading package lists... Done
+ apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 http://ppa.launchpad.net/canonical-server/server-backports/ubuntu focal InRelease
Hit:7 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease
Reading package lists... Done
+ apt-get install -y jq
Reading package lists... Done
Building dependency tree
Reading state information... Done
jq is already the newest version (1.6-1ubuntu0.20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
+ apt-get install -y virt-what
Reading package lists... Done
Building dependency tree
Reading state information... Done
virt-what is already the newest version (1.19-1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
+ apt-get install -y mingetty
Reading package lists... Done
Building dependency tree
Reading state information... Done
mingetty is already the newest version (1.08-2build1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
+ apt-get install -y python3-dev python3-venv python3-setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-venv is already the newest version (3.8.2-0ubuntu2).
python3-setuptools is already the newest version (45.2.0-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
+ [[ ! -d /home/gns3/.venv/gns3server-venv ]]
+ apt-get install -y --allow-change-held-packages libvirt-daemon-system
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libvirt-daemon-system : Depends: polkitd (>= 121+compat0.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR DURING THE UPGRADE PROCESS PLEASE, TAKE A SCREENSHOT IF YOU NEED SUPPORT

**Comment by grossmj** [comment] 2024-07-23 16:05
> I we able to resolve by running "sudo gns3restore" and have successfully upgraded to 2.2.48.1

I was not able to reproduce the issue and I haven't got other people complaining about it. I will close this since you managed to fix this on your end ;)

**Closed by grossmj** 2024-07-23 16:05 UTC
