### ISSUE TITLE
Latest L2IOU "failed code signing checks"

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-server#1484] opened 2018-12-17 05:36 UTC
Latest version of L2IOU does not work in GNS3, it stops forwarding traffic with the error:

"%PLATFORM-2-SIGNATURE_FAILED: Image '' failed code signing checks, error 'Failure in opening the file'. Ethernet switching has been disabled to protect against attack."

Please note, it works well using the Cisco wrapper.

**Comment by grossmj** [comment] 2018-12-17 05:39
What is the filename? Maybe Cisco has implemented some kind of protection...

**Comment by AdrianSimionov** [comment] 2018-12-17 05:46
This is the version where I am experiencing the problem.

Cisco IOS Software, Linux Software (I86BI_LINUXL2-ADVENTERPRISEK9-M), Version 15.2(CML_NIGHTLY_20180510)FLO_DSGS7, EARLY DEPLOYMENT DEVELOPMENT BUILD, synced to  V152_6_0_81_E
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2018 by Cisco Systems, Inc.
Compiled Thu 10-May-18 02:45 by mmen

**Comment by AdrianSimionov** [comment] 2018-12-17 06:10
My tests show that when the image is started in the format ./FILENAME, it works. It does not matter if the wrapper is used or not. Any other path with the exception of "./" will fail.

**Comment by grossmj** [comment] 2018-12-17 06:11
Thanks for the feedback. I will try soon and see if there is any workaround we can implement.

**Comment by grossmj** [comment] 2018-12-18 03:56
I was able to run this image without any issue. Do you get this error after a while and how is connected your IOU node?

```
IOU1#show version 
Cisco IOS Software, Linux Software (I86BI_LINUXL2-ADVENTERPRISEK9-M), Version 15.2(CML_NIGHTLY_20180510)FLO_DSGS7, EARLY DEPLOYMENT DEVELOPMENT BUILD, synced to  V152_6_0_81_E
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2018 by Cisco Systems, Inc.
Compiled Thu 10-May-18 02:45 by mmen
```

**Comment by AdrianSimionov** [comment] 2018-12-18 03:58
The image starts but no packets are forwarded. If I wait a bit, CDP will expire, Wireshark will show no packets passing.

Can you confirm the packets are passing between two attached Switches?

**Comment by grossmj** [comment] 2018-12-18 03:58
Sorry, I hadn't noticed I got the error in the boot messages:

```
*Dec 18 03:53:09.775: %PLATFORM-2-SIGNATURE_FAILED: Image '/i86bi_LinuxL2-AdvEnterpriseK9-M_152_May_2018.bin' failed code signing checks, error 'Failure in opening the file'. Ethernet switching has been disabled to protect against attack.
```

**Comment by AdrianSimionov** [comment] 2018-12-18 04:01
That is the issue. And once you get that error, my experience is that all packets are dropped.

**Comment by grossmj** [comment] 2018-12-18 04:45
The workaround works well. I was able to pass traffic between 2 nodes. 

We can close this now. The fix will be in version 2.1.12.

**Comment by AdrianSimionov** [comment] 2019-01-01 23:46
> when is the next version coming out, please

+1

**Comment by grossmj** [comment] 2019-01-02 16:35
Next version will be out before January 15 unless there is an unexpected issue.

**Comment by ccie59071** [comment] 2019-01-17 15:10
> Next version will be out before January 15 unless there is an unexpected issue.

any news about the new version

**Comment by Pery004** [comment] 2021-02-10 03:33
Hi all,
could someone tell me how to solve this on VMware pro 16 with Windows 10 host??
i only found 2 threads like this on google, but still have no idea

sorry for my poor english

**Comment by andrei-korshikov** [comment] 2023-10-15 17:45
Found this issue while reading the GNS3 source code. For your information:

- **IOU file base name length must be <= 63 chars**
- - +1 mandatory `/` character, so 64 characters total
- maximum length example: `/i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510abc.bin`
- more lengthy basename leads to `%PLATFORM-2-SIGNATURE_FAILED: Image '/YOUR_LENGTHY_FILE_NAME' failed code signing checks, error 'Failure in opening the file'. Ethernet switching has been disabled to protect against attack.` message

So, with [current solution](https://github.com/GNS3/gns3-server/blob/2c5a9ef9b7df738f07c07ad8382e94950ad4fc7b/gns3server/compute/iou/iou_vm.py#L539) (symlinks) it is possible to get "Failure in opening the file" error if your file name (base name) is too long.

My proposal is:
- check the base name length
- truncate symbolic link name to 63 symbols if needed (so user can have long file name in their archive, but GNS3 still can execute such file)

Or just throw away symlink creation, and don't allow user to add IOU images with base names > 63 symbols.

@grossmj Is it possible to reopen this issue?

**Comment by grossmj** [comment] 2023-10-24 04:13
@andrei-korshikov Please can you share the i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510abc.bin image? thanks.

**Comment by andrei-korshikov** [comment] 2023-10-24 08:37
Jeremy, I'm really sorry if I've deceived you. The real file name of the image I mentioned is `i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510.FLO_DSGS7.bin` (70 characters, plus `/` - that is why I've got this issue several years ago), it's md5 is `d704b68c5f4c4f92e56b754b49b92012` - the same image this thread have begun with. Looking at your examples - `i86bi_LinuxL2-AdvEnterpriseK9-M_152_May_2018.bin` - I think you already have it:) or if you still need it - please, send me an email to andrej.s.korshikov@gmail.com. By the way, as far as I can tell, all L2 CML_NIGHTLY images have 70-chars names, their difference only in version numbers (151 vs 152) and dates (20150703, 20151103, 20151103, 20160628, 20180510).

**Comment by grossmj** [comment] 2023-10-24 08:43
> Jeremy, I'm really sorry if I've deceived you. 

No worries at all :) I will contact you for the IOU image. Thanks 👍

**Comment by grossmj** [comment] 2023-10-25 07:03
> *Oct 25 07:00:15.169: %PLATFORM-5-SIGNATURE_VERIFIED: Image '/i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510.bin' passed code signing verification

Sorry, I tried with the image you sent me and I don't have issues because the name is 61 characters and renaming the image to make it longer doesn't work.

I guess I need the one named "i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510.FLO_DSGS7.bin" to reproduce the problem.

Thanks :)

**Comment by andrei-korshikov** [comment] 2023-10-25 21:40
Yes, that is why I renamed "i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510.FLO_DSGS7.bin" to "i86bi_linuxl2-adventerprisek9-m.152-CML_NIGHTLY_20180510.bin". Than added one symbol at a time and - boom - here was the limit:)

**Comment by grossmj** [comment] 2023-10-26 05:13
Fixed, thanks again for finding this issue 👍

**Closed by grossmj** 2023-10-26 05:13 UTC
Labels: Bug
