### ISSUE TITLE
BPF packet filter: with each new expression it hangs for a while.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1283] opened 2018-02-01 12:25 UTC
As soon as I set a new BPF expression on the link,  it hangs for a while trying to download something (~20 MB):

![selection_011_01_02](https://user-images.githubusercontent.com/1716020/35677773-39ef7510-0751-11e8-944c-3f85b7e24f76.jpg)

![image](https://user-images.githubusercontent.com/1716020/35677804-5b1ce43e-0751-11e8-8606-e7ebedbccabc.png)

![selection_012_01_02](https://user-images.githubusercontent.com/1716020/35678350-43c08f3c-0753-11e8-883a-5334a549d5bf.jpg)

After a while, the filter is applied.

**Comment by grossmj** [comment] 2018-02-02 08:48
Does it happen only between Docker containers?

**Comment by AJNOURI** [comment] 2018-02-05 13:50
Hey @grossmj,

Tested IOS, IOSv and IOU
![selection_006_05_02](https://user-images.githubusercontent.com/1716020/35807504-493e7c52-0a83-11e8-9737-4578f56e9f0d.jpg)


and for both IOU and IOS (dynamips) I got errors cannot apply the filter:
![selection_005_05_02](https://user-images.githubusercontent.com/1716020/35807512-4d45e718-0a83-11e8-8917-8e1e33304b36.jpg)

By the way, I've tried "ip proto icmp" with and without double quotes and with escaping icmp (ip proto \icmp) .

For IOSv I don;t have the above mentioned error, but link doesn't seem to filter anything.

The closest to a working filter was with containers, except the timeout and hanging, but afterward working filter.

**Comment by grossmj** [comment] 2018-02-06 09:25
You should only use `icmp`

I was not able to reproduce the hanging and timeout so far.

**Comment by grossmj** [comment] 2018-03-14 11:28
@AJNOURI do you still have this issue with version 2.1.4?

**Comment by AJNOURI** [comment] 2018-03-15 16:16
Hi @grossmj ,

Tested the filter for Containers, IOS (dynamips) and IOU with various filters:
Works like a charm. 
![selection_003_15_03](https://user-images.githubusercontent.com/1716020/37476101-9ab193c6-2874-11e8-9e04-050cf15702fd.jpg)


Good job!!

**Comment by grossmj** [comment] 2018-03-15 16:18
Ok, thanks for confirmation. I will close this issue.

**Closed by grossmj** 2018-03-15 16:18 UTC
Labels: Bug, Waiting for more information
