### ISSUE TITLE
Cannot start console application: AUX console port not allocated for

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1281] opened 2018-01-31 01:02 UTC
Sometimes, as soon as I see the container UP (upon start) I invoke AUX console, before console port is allocated, the project closes abruptly

![image](https://user-images.githubusercontent.com/1716020/35599647-1485fbbe-062a-11e8-8ca9-3c122e04b647.png)

We could maybe anticipate the event and delay the request or just show a warning for the user to wait or retry in a couple of seconds.

--------------
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

Running GNS3 version 2.1.4dev1 on Linux (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.2.

**Comment by AJNOURI** [comment] 2018-01-31 01:17
Looks like the same behavior, I close the project and reopen and as soon as the topology is drawn in the canvas I click "start"

Not all containers are loaded and I catch the error:

> ajn@~/gns3-gui$ gns3
> 2018-01-31 02:11:46 INFO root:126 Log level: INFO
> 2018-01-31 02:11:46 INFO main:258 GNS3 GUI version 2.1.4dev1
> 2018-01-31 02:11:46 INFO main:259 Copyright (c) 2007-2018 GNS3 Technologies Inc.
> 2018-01-31 02:11:46 INFO main:261 Application started with /usr/local/bin/gns3
> 2018-01-31 02:11:55 ERROR http_client:682 Docker has returned an error: 404 No such container: 9f65a7ae173a67173d41e42b447bd97933023c42c30dcf1cdf10c90358a7de5a

**Comment by grossmj** [comment] 2018-01-31 05:36
You must be fast, how many containers are you trying to start at the same time? Are they slow to start?

**Comment by AJNOURI** [comment] 2018-02-01 12:07
There are only three containers. The project is loaded normally (maybe 2 sec) as far as the devices are correctly drawn, I click start.
And for the console, as soon as the device link is green I try to console to the started device.

**Comment by grossmj** [comment] 2018-02-02 08:33
Looks like the root of the problem is we don't wait that the Docker containers are stopped when closing the project and opening another. This cause issues when opening the same project again.

**Comment by grossmj** [comment] 2018-02-02 08:44
> Sometimes, as soon as I see the container UP (upon start) I invoke AUX console, before console port is allocated, the project closes abruptly

Does it happen when you open a project when you already running one?

**Comment by grossmj** [comment] 2018-02-07 08:05
Looks like we do not wait for a project to be closed before doing something else, Project close() method is never called: https://github.com/GNS3/gns3-gui/blob/2.1/gns3/project.py#L487

There may be some refactoring to do. We will wait 2.2 to avoid breaking something.

**Closed** 2020-07-18 11:41 UTC
Labels: Bug
