### ISSUE TITLE
[GNS3 2.6.6][Python type error] Configure template -> Network -> Configure custom adapters

### ISSUE THREAD

**Issue by jhonnyx82** [GNS3/gns3-server#1733] opened 2020-04-05 12:15 UTC
I am running GNS3 2.2.6 and when I want to edit a template custom network adapters I receive the following error:

GUI is on Windows 10
Server is on Physical Debian 10 

EDIT : I tried also with the linux client but it does not drop any traceback but it still does not let me edit the template

Not sure if this is an error on the server or on the client
```
PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_configuration_page.py", line 404, in _customAdaptersConfigurationSlot
TypeError: 'NoneType' object is not subscriptable
```

**Comment by grossmj** [comment] 2020-04-05 13:12
What is the template type? (Qemu, Dynamips etc.)

Thanks.

**Comment by jhonnyx82** [comment] 2020-04-05 13:23
Hi Jeremy,

template is QEMU

**Comment by grossmj** [comment] 2020-04-07 06:05
Duplicate of https://github.com/GNS3/gns3-gui/issues/2961

**Closed by grossmj** 2020-04-07 06:05 UTC
Labels: Duplicate
