### ISSUE TITLE
Dynamips and Qemu errors

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-server#1809] opened 2020-08-12 18:04 UTC
Hi GNS3 Team,

Can you kindly help, have installed dynamips ver: 0.2.18-1~xenial1, when starting devices, getting error: 
**Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605**
Qemu:
qemu installed: 1:5.0-6, but getting below error
**Sorry, no QEMU binary has been found. Please make sure QEMU is installed before continuing**

OS: Linux
GNS3: 2.2.11, 2.2.12 not installing.
Thanks

**Comment by grossmj** [comment] 2020-09-06 15:29
Duplicate of https://github.com/GNS3/gns3-gui/issues/3041

**Closed by grossmj** 2020-09-06 15:29 UTC
Labels: Duplicate
