### ISSUE TITLE
VMnet not working in cloud node on Windows

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#989] opened 2017-04-28 10:57 UTC
If you try asking for DHCP via a cloud interface VMnet8 (Nat) you will get your own packet back.

**Comment by noplay** [comment] 2017-05-12 06:34
I have no idea why it's not working :(

**Comment by grossmj** [comment] 2017-05-12 06:59
Looped packets due to winpcap?

**Comment by noplay** [comment] 2017-05-12 07:00
Yes

Le ven. 12 mai 2017 à 08:59, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment] 2017-05-12 07:02
Worth a try with npcap maybe.

**Comment by grossmj** [comment] 2017-08-30 15:03
Duplicate of https://github.com/GNS3/gns3-gui/issues/2228

**Closed by grossmj** 2017-08-30 15:03 UTC
Labels: Bug, Duplicate
