### ISSUE TITLE
How to I change the default network on the Dock0 interface. GNS3 VM 2.0

### ISSUE THREAD

**Issue by dkhenderson2** [GNS3/gns3-server#1012] opened 2017-05-04 17:27 UTC
Currently the Default network on the Docker0 interface is 172.17.0.0/16. This conflicts with many of my internal networks. Most importantly the subnet of the floor on which I work. 172.17.50.0. Because of this I cannot access the GNS3 VM because of my traffic is funneled to the Docker0 interface.

![docker0 interface](https://cloud.githubusercontent.com/assets/21106062/25716515/4b8d5dd8-30cd-11e7-93c2-f40295d37b8e.png)

I have tried the fix at this site:

https://support.zenoss.com/hc/en-us/articles/203582809-How-to-Change-the-Default-Docker-Subnet?mobile_site=true

But it only temporary changes the IP. Everything reverts after a reboot which is required after making changes to networking.

There is mention of a file in /etc/sysconfig/docker that if the changes are made there it would be permenant. But that directory does not exist on the GNS3 VM

**Comment by noplay** [comment] 2017-05-05 12:59
Closed: https://gns3.com/qa/how-to-i-change-the-defualt-netw

It's duplicate of the forum discussion.

**Closed by noplay** 2017-05-05 12:59 UTC
Labels: Duplicate
