### ISSUE TITLE
Feature Request: Add basic authentication for project

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-server#1554] opened 2019-03-17 22:29 UTC
Hi Team,

When using GNS3 as a shared server among many users, integrity of a project becomes more tricky to avoid if one user accidentally destroy other user work. Adding project basic authentication is a good integrity measure.

I understand this is a major change to the REST API.
This is not a high priority requirements, but more a best effort.

Doron

**Comment by grossmj** [comment] 2019-03-18 07:50
We have plans to add user management (rights, usage limitation etc..) to the GNS3 server but like you said, there will be a major REST API change.

**Comment by srieger1** [comment] 2019-09-04 20:12
We have similar problems using GNS3 in our network laboratory at Fulda University of Applied Sciences. Looking forward to see improvements regarding the user management in GNS3. However, Doron, if you like, you can take a look at the interim solution we developed that acts as a proxy in front of GNS3 backends: https://github.com/srieger1/gns3-proxy. The deny rules of the proxy can be used to implement the protection you mentioned while we're waiting for GNS3 >= 2.4 ;)

**Comment by grossmj** [comment] 2019-10-30 07:33
Comment from B3r3n:

I think it would be good to have at least 2 level of privileges : admin and non-admin, authentication requested by client if not defined into the configuration file. Control would be basic : either user can only create/manage his project(s), either he's admin and then able to import/change/delete appliances/templates/projects etc. Associated with this, each project could contain a user list that would define if user can or not update projects (teacher vs simple students).

**Comment by grossmj** [comment] 2020-01-30 08:13
Related to https://github.com/GNS3/gns3-server/issues/1337

**Comment by grossmj** [comment] 2020-11-02 08:20
Duplicate of https://github.com/GNS3/gns3-server/issues/1337

**Closed by grossmj** 2020-11-02 08:20 UTC
Labels: Duplicate, Enhancement
